### ISSUE TITLE
Open in New Tab not working

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#10004]
Open [any NFT](https://kodadot.xyz/ahp/gallery/115-2404190282). Click on open in a new tab - it is not working. 

<img width="1450" alt="Screenshot 2024-04-05 at 13 32 50" src="https://github.com/kodadot/nft-gallery/assets/104380776/2be1bcdc-00df-4fcd-a2bc-93c27e89de62">

**Comment by exezbcz** [comment]
wouuld probably need rewriting the whole component from here:
- https://github.com/kodadot/nft-gallery/pull/9809

**Comment by hamidovz** [comment]
is this fixed ? because that feature works in local dev environment

**Comment by exezbcz** [comment]
@hamidovz does not work here 
https://kodadot.xyz/ahp/gallery/115-2404190282

**Comment by hamidovz** [comment]
@exezbcz ah i see. the problem is nftMimeType is empty so  handleNewTab method can't get value of src attribute;

**Comment by hamidovz** [comment]
@exezbcz the problem is: some of the response doesn't include mimeType. for example:

1) request to **https://image-beta.w.kodadot.xyz/type/endpoint/https://fxart-beta.kodadot.workers.dev/metadata/v1/json?chain=ahp&collection=115&nft=2404739348&metadata=ipfs:%2F%2Fbafybeiahv7ezqzhizpyctgwav5uf4qi3h6gynwr7tc5tglnmjbuqf3emdm%2F0.json**

**Response:** 

`{
  "name": "Tilescapes #54",
  "description": "Artist: [Thomas Art](https://twitter.com/Th0mas_Art) \n\n\n Tilescape is a captivating generative art project that delves into the realm of simplicity and geometry. Each artwork within Tilescape is meticulously crafted using only basic geometric shapes such as squares and rectangles. These minimalist elements are arranged algorithmically to create sophisticated compositions that evoke a sense of both order and creativity. Through the harmonious interplay of shapes and colors, Tilescape invites viewers to immerse themselves in a world that unveils mesmerizing landscapes of form and pattern",
  "image": "ipfs://bafybeiehvbuuygkmfmjtlzzrohzqhhidxro7xebfdy3dukyrikabeb5n3m/0.png",
  "animation_url": "ipfs://bafybeifb752b5i7v4gxrawuovujtt6hrmgkdtzfwi5lfiph7jnbk4xomli/?hash=0x9a95d2afc8210972334aa5d597bd5e1bb54c58e0f6ecbce44b92f10ab2bb8219",
  "attributes": [],
  "external_url": "kodadot.xyz",
  "type": "text/html"
}`


2) request to **https://image-beta.w.kodadot.xyz/metadata?url=https%3A%2F%2Fimage-beta.w.kodadot.xyz%2Fipfs%2Fbafybeif5jyvht3hxwhwcfvxizux3z7qkc2pe4wijcwqvxqxllaqnqbwe54%2F985.json**





**Response:**

`{
  "imageMimeType": "image/jpeg",
  "animationUrlMimeType": "text/html",
  "description": "**.motherboard** reimagines the motherboard as refined art, expressing it as dynamic digital art. The sophisticated arrangement of the motherboard's components and circuit patterns, striving for efficiency, can be considered a marvelous fusion of technology and art.\n\n\nIn this piece, I depict the vias and sections of the electronic board through recursive functions. The patterns, drawn by a palette of 37 colors and mathematical formulas, visually represent the harmony between the technical intricacies and aesthetics embedded in each component. It goes beyond being a mere component of a machine; it symbolizes admiration for the beauty of digital culture. \n\n\nThrough this artwork, I sought to explore the mystery and aesthetics of generative art in digital animation. The patterns generated by hash and formulas showcase the potential for different outcomes, akin to the absence of a single perfect solution in physical motherboards. The commitment to pursuing the highest beauty within the constraints of technology, materials, and limited space is, I believe, a crucial aspect in any form of craftsmanship. \n\n\nGenerative art by [@dotconatus](https://twitter.com/dotconatus) \n\n\nBuilt in Javascript with p5.js.",
  "image": "https://image-beta.w.kodadot.xyz/ipfs/bafybeiatfptzax365kqhgvs4oyjzq4psfxoozlly74crqyd23fevpdnbai/985.jpeg",
  "animationUrl": "https://image-beta.w.kodadot.xyz/ipfs/bafybeihdrwq23xxtolehk7rmwvd4bkvq6dpidzfpox4dhtknfn3igajnza/?hash=0x13ca715b471815c8cda96a684961f90ab47f1bae59335471fb79da5a71c498bb",
  "attributes": [],
  "name": ".motherboard #985",
  "type": "text/html",
  "externalUrl": "kodadot.xyz",
  "tags": [],
  "thumbnail": "",
  "_raw": {
    "name": ".motherboard #985",
    "description": "**.motherboard** reimagines the motherboard as refined art, expressing it as dynamic digital art. The sophisticated arrangement of the motherboard's components and circuit patterns, striving for efficiency, can be considered a marvelous fusion of technology and art.\n\n\nIn this piece, I depict the vias and sections of the electronic board through recursive functions. The patterns, drawn by a palette of 37 colors and mathematical formulas, visually represent the harmony between the technical intricacies and aesthetics embedded in each component. It goes beyond being a mere component of a machine; it symbolizes admiration for the beauty of digital culture. \n\n\nThrough this artwork, I sought to explore the mystery and aesthetics of generative art in digital animation. The patterns generated by hash and formulas showcase the potential for different outcomes, akin to the absence of a single perfect solution in physical motherboards. The commitment to pursuing the highest beauty within the constraints of technology, materials, and limited space is, I believe, a crucial aspect in any form of craftsmanship. \n\n\nGenerative art by [@dotconatus](https://twitter.com/dotconatus) \n\n\nBuilt in Javascript with p5.js.",
    "image": "ipfs://bafybeiatfptzax365kqhgvs4oyjzq4psfxoozlly74crqyd23fevpdnbai/985.jpeg",
    "animation_url": "ipfs://bafybeihdrwq23xxtolehk7rmwvd4bkvq6dpidzfpox4dhtknfn3igajnza/?hash=0x13ca715b471815c8cda96a684961f90ab47f1bae59335471fb79da5a71c498bb",
    "type": "text/html",
    "external_url": "kodadot.xyz"
  }
}`


since i can't find the server codes , i can implement workaround by getting mimetype according the ending of the image url. if this is acceptable , i can proceed

**Comment by vikiival** [comment]
[the code is here](https://github.com/kodadot/workers/tree/main/image)

**Comment by hamidovz** [comment]
@vikiival hi! I fixed it but i need to change base of ntf-gallery to my local worker url to ensure it works with client side. Normally base urls would be located in .env variable but i can't find it in nft-gallery repo. Can you help me to change baseurl please  ?

**Comment by Jarsen136** [comment]
There is a simple way to fix it on the frontend https://github.com/kodadot/nft-gallery/pull/10077
