### ISSUE TITLE
Same sn number

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#10025]
I tried mass mint on production and got the same number?
- https://assethub-polkadot.subscan.io/extrinsic/0xab743002b51db1bce5b2809fda73bf02924806ba953cb5fe3fdbb4b8e4b96228

<img width="245" alt="image" src="https://github.com/kodadot/nft-gallery/assets/5887929/eee51c60-6d2e-4b2a-a479-34e38c4d6434">

**Comment by preschian** [comment]
which modal is this? seems like bug on frontend side. because backend side looks fine

extrinsic: https://assethub-polkadot.subscan.io/extrinsic/6019167-2

metadata:
- https://fxart-beta.kodadot.workers.dev/metadata/v1/json?chain=ahp&collection=115&nft=2404137707&metadata=ipfs:%2F%2Fbafybeibc647umpxu3z5ilfaq2x2lteiw5ewngmn2avlfb5flyti7rgkrja%2F0.json
- https://fxart-beta.kodadot.workers.dev/metadata/v1/json?chain=ahp&collection=115&nft=2404178937&metadata=ipfs:%2F%2Fbafybeibc647umpxu3z5ilfaq2x2lteiw5ewngmn2avlfb5flyti7rgkrja%2F1.json
- https://fxart-beta.kodadot.workers.dev/metadata/v1/json?chain=ahp&collection=115&nft=2404266462&metadata=ipfs:%2F%2Fbafybeibc647umpxu3z5ilfaq2x2lteiw5ewngmn2avlfb5flyti7rgkrja%2F5.json
- https://fxart-beta.kodadot.workers.dev/metadata/v1/json?chain=ahp&collection=115&nft=2404333247&metadata=ipfs:%2F%2Fbafybeibc647umpxu3z5ilfaq2x2lteiw5ewngmn2avlfb5flyti7rgkrja%2F4.json
- https://fxart-beta.kodadot.workers.dev/metadata/v1/json?chain=ahp&collection=115&nft=2404366389&metadata=ipfs:%2F%2Fbafybeibc647umpxu3z5ilfaq2x2lteiw5ewngmn2avlfb5flyti7rgkrja%2F2.json
- https://fxart-beta.kodadot.workers.dev/metadata/v1/json?chain=ahp&collection=115&nft=2404732533&metadata=ipfs:%2F%2Fbafybeibc647umpxu3z5ilfaq2x2lteiw5ewngmn2avlfb5flyti7rgkrja%2F3.json

**Comment by preschian** [comment]
oohh, wait checking~

nft with id `2404137707` should be `#87`

from indexer returns `#88`

![Capture-2024-04-08-201704](https://github.com/kodadot/nft-gallery/assets/734428/3cd3ce29-df9c-4cd9-a448-0a900dd2a998)

**Comment by preschian** [comment]
fixed
