### ISSUE TITLE
Tilescapes - Indexing mints

### ISSUE THREAD

**Issue by ThomasssArt** [kodadot/nft-gallery#10064]
### Is there an existing issue?

- [X] I have searched the existing issues

### What happened?

Most bugs for Tilescapes are fixed. Unfortunately there are still some problems with "indexing".

Some works didnt get any index:
![image](https://github.com/kodadot/nft-gallery/assets/60002234/f1ab1e7e-22a8-464c-96c3-a0c796110e42)

There are works with the same index (--> #88 & #88 instead of #87 & #88)
![image](https://github.com/kodadot/nft-gallery/assets/60002234/64f3c94c-a4fa-4711-9626-0d343e59faaf)

I would also expect the indexing to be in ascending/descending order (not #85 #86 #91 #92 #90,...):
![image](https://github.com/kodadot/nft-gallery/assets/60002234/567a17bc-bd04-46c1-b381-66380acbec25)

### Please reproduce in steps

Just visit Tilescapes:
https://kodadot.xyz/ahp/drops/tilescape

### Expected Behavior

Proper indexing

### What browsers are you seeing the problem on?

Desktop Chrome

### At which address did you encounter bug?

kodadot.xyz

### Are you logged in?

None

### Which wallet you are using?

Talisman

### At which chain did you encounter bug?

Asset Hub Polkadot

### Screenshots

Screenshots added above

### Payment link for reward

https://canary.kodadot.xyz/dot/transfer/?target=13sKcT6tSFRR6HfonaTt4pahd8J4q2m7Q4Kq2FPvzLWh9N7 https://github.com/kodadot/nft-gallery/blob/main/REWARDS.md#creating-your-dot-address>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by exezbcz** [comment]
anything that can be made @kodadot/internal-dev ? 👀

**Comment by preschian** [comment]
To view the correct index/serial number, visit the gallery item page. It will be fixed in this PR: https://github.com/kodadot/nft-gallery/pull/10087

These items are marked as `#88` from the graphql query. If you visit this page, it will change the name with the correct index/serial numbers
- https://deploy-preview-10087--koda-canary.netlify.app/ahp/gallery/115-2404333247
- https://deploy-preview-10087--koda-canary.netlify.app/ahp/gallery/115-2404137707

There is still an issue on the query side here: https://github.com/kodadot/stick/issues/267#issuecomment-2043433047. It only affected mass mint/claim

**Comment by ThomasssArt** [comment]
Perfect, thanks!
