### ISSUE TITLE
Electronik: Wrong view

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#10108]
Something is off with these [NFTs](https://canary.kodadot.xyz/ahp/gallery/121-2404190324). Their size is not good.

<img width="1869" alt="Screenshot 2024-04-19 at 15 43 27" src="https://github.com/kodadot/nft-gallery/assets/104380776/c603f31d-7ce0-42dd-83d1-e51badddcbab">
<img width="1850" alt="Screenshot 2024-04-19 at 15 43 46" src="https://github.com/kodadot/nft-gallery/assets/104380776/51dcdda8-f707-4d74-9e4b-4fe1566214ae">

**Comment by hassnian** [comment]
@JustLuuuu will be fixed by https://github.com/kodadot/nft-gallery/pull/10075

https://deploy-preview-10075--koda-canary.netlify.app/ahp/gallery/121-2404190324

![CleanShot 2024-04-20 at 10 22 30@2x](https://github.com/kodadot/nft-gallery/assets/44554284/39b9141b-4239-470e-b41a-731d292934a0)

![CleanShot 2024-04-20 at 10 22 12@2x](https://github.com/kodadot/nft-gallery/assets/44554284/6fe65fe9-1133-4c7f-9902-b4c052aa37d5)

**Comment by hassnian** [comment]
fixed by #10075
