### ISSUE TITLE
Aurora drop sn 13 not loading

### ISSUE THREAD

**Issue by prury** [kodadot/nft-gallery#10144]
https://kodadot.xyz/ahp/gallery/120-2404230758

![image](https://github.com/kodadot/nft-gallery/assets/36627808/7c7a0f1f-fa01-4c51-a52a-e20b0af6c67e)

console: 

![image](https://github.com/kodadot/nft-gallery/assets/36627808/b8e17f49-7399-494c-8d8b-e08607338397)

**Comment by preschian** [comment]
Fixed on canary, just need to deploy to production

**Comment by preschian** [comment]
It seems like a valid issue. In this item, html was fine, but not the image:
- https://fxart-beta.kodadot.workers.dev/metadata/v2/image?chain=ahp&collection=121&hash=0xdfa3dbac067c440c6300c38046fee5505cbd81d5b24d99f81e5ace2eabc9e3f9
- https://canary.kodadot.xyz/ahp/gallery/121-2404247187

**Comment by preschian** [comment]
> It seems like a valid issue. In this item, html was fine, but not the image:

After further checking, capture workers could not get the image from `Elekctonik` drops. Puppeteer on Workers seems to have some limitations compared to Puppeteer on Node.js.

The other drops so far look fine. To prevent this issue in the future, can we put an image preview with capture workers under `/code-checker` for now?

endpoint: https://capture.kodadot.art/screenshot
example request: https://github.com/kodadot/private-workers/blob/ea7780e127ba7b8eec5af7115cb579c9a7889c75/fxart/src/routes/drops-metadata-v2.ts#L101-L109

**Comment by prury** [comment]
https://canary.kodadot.xyz/ahp/gallery/121-2404119362

**Comment by preschian** [comment]
> To prevent this issue in the future, can we put an image preview with capture workers under `/code-checker` for now?

Can someone add a `capture-worker` checker below the `/code-checker` page? It would be good if we could generate ten previews for both animation and static images below the page cc @kodadot/internal-dev 

any hash on `Electronik` drops doesn't work on `capture-worker`
`https://image.w.kodadot.xyz/ipfs/bafybeifyzbjdvfblvs7eowr52w5i77yvro3c7cg7inyksem6kcxqjj6zdu/?hash={hash}`

Or maybe anyone has some workaround, and the code is here: https://github.com/kodadot/workers/blob/f9f64dbb1390485f1de8557d6a3c13ae0a81feb6/capture/src/utils/surf.ts#L25-L39.

I already tried some approaches, such as listening to `console.log` on the page, which doesn't work with puppeteer on workers instead of puppeteer on node.js

**Comment by preschian** [comment]
> Moreover, code-chcecker already checks for WEBGL related stuff.

marked as "Not Using WebGL" here  https://github.com/kodadot/ops-internal/issues/1579#issuecomment-2058519609

**Comment by preschian** [comment]
oh nvm, the newer version was webgl

<img width="898" alt="Screenshot 2024-05-01 at 14 13 11" src="https://github.com/kodadot/nft-gallery/assets/734428/6bdcb274-3b74-4c50-a19e-8b67df1fe65b">

**Comment by preschian** [comment]
same issue: https://github.com/kodadot/nft-gallery/issues/10097

**Comment by preschian** [comment]
> [canary.kodadot.xyz/ahp/gallery/121-2404119362](https://canary.kodadot.xyz/ahp/gallery/121-2404119362)

updated, manually upload the image

**Comment by preschian** [comment]
> The other drops so far look fine. To prevent this issue in the future, can we put an image preview with capture workers under `/code-checker` for now?

I think we still need this
