### ISSUE TITLE
Only a few images loading on HDD

### ISSUE THREAD

**Issue by prury** [kodadot/nft-gallery#10188]
is it only here? or is it happening with everyone? 
also, lots of similar images
@kodadot/internal-dev 

![image](https://github.com/kodadot/nft-gallery/assets/36627808/321c35e0-1a6d-43e7-b956-962f02bf4496)

**Comment by vikiival** [comment]
@preschian

**Comment by preschian** [comment]
for images similar with this https://github.com/kodadot/nft-gallery/issues/10144#issuecomment-2080369550

puppeter on workers not perfectly fine. should we use that vercel one for capture? @vikiival 

for items that doesn't have serial numbers will be fixed in here https://github.com/kodadot/private-workers/issues/121#issuecomment-2088442621

**Comment by preschian** [comment]
If puppeteer on Deno can give the same capabilities as node.js, I can try to spin up on Deno

**Comment by preschian** [comment]
most of them should be already backfilled

<img width="2168" alt="Screenshot 2024-05-02 at 21 33 53" src="https://github.com/kodadot/nft-gallery/assets/734428/61b267c7-ddc2-4c93-ad59-bc797a1a10d7">

**Comment by vikiival** [comment]
cc @preschian 
- https://github.com/kodadot/private-workers/issues/136

**Comment by preschian** [comment]
updated

1. preview images
for now. Let's use Puppeteer on non-serverless infra

2. serial numbers
fixed here:
https://assethub-polkadot.subscan.io/extrinsic/6210495-2
https://assethub-polkadot.subscan.io/extrinsic/6210576-3
currently, some scripts are running every hour to address this issue. Once the script looks good, I will move the script to the private-workers
