### ISSUE TITLE
Base drop: strigae - missing mints

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#10463]
A guy minted one NFT and he didn't see his NFT after minting.

<img width="594" alt="Screenshot 2024-06-12 at 13 09 39" src="https://github.com/kodadot/nft-gallery/assets/104380776/cfb7d281-f267-45d5-9ab8-ee7ad8f2dca1">

Collection
---
**Drop link**: https://warpcast.com/antoniowerli/0xf666170a
**Collection on Koda**: https://kodadot.xyz/base/collection/0xb67bedc5e80a7913b92da0a56fc8aba6c1273a6a?page=Infinity

My test
---

I tried to mint one today - it worked but it has number # 2 and **# 0 and # 1 are missing** - WHERE are they?
<img width="1668" alt="Screenshot 2024-06-12 at 13 11 31" src="https://github.com/kodadot/nft-gallery/assets/104380776/c63e3b1d-7f7f-45cf-b63f-b532f936e5ec">

**Comment by preschian** [comment]
Actually, the genart/animation is not missing. The missing one is only thumbnails. I already updated the thumbnails, and they should look fine now.

This is how it looks on OpenSea:

| before "refresh metadata" | after "refresh metadata" |
|--------|--------|
| <img width="2672" alt="Screenshot 2024-06-13 at 14 59 53" src="https://github.com/kodadot/nft-gallery/assets/734428/dd04f2d6-bce7-4044-93a0-39593f4078f0"> | <img width="2672" alt="Screenshot 2024-06-13 at 15 07 27" src="https://github.com/kodadot/nft-gallery/assets/734428/7fdf86e6-4125-4a75-b6a2-ab0ffccbd0be"> | 

Please note that our platform is not yet optimised for base. For example, the thumbnail is probably still using the old one instead of the new one. Will working on it

**Comment by vikiival** [comment]
> WHERE are they?

hey,
The NFTs were minted before the collection was registered, 
I need to upadate the indexer to process it :)

**Comment by preschian** [comment]
> can you please purge cache ?

updated

<img width="2672" alt="Screenshot 2024-06-13 at 16 50 18" src="https://github.com/kodadot/nft-gallery/assets/734428/4777903b-95e0-4faa-bf87-50dc742ba16f">

**Comment by vikiival** [comment]
Made fix on indexer 
- https://github.com/kodadot/basick/pull/25/files

**Comment by preschian** [comment]
already showup on koda
