### ISSUE TITLE
Profiles: Working?

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#10633]
Message from two days ago from artist who already tried to create his profile twice:

<img width="600" alt="Screenshot 2024-07-16 at 12 59 37" src="https://github.com/user-attachments/assets/6dac1b4f-8f30-4fdc-9079-47782c83b7b1">

What is the status of the profiles?

**Comment by Jarsen136** [comment]
> Message from two days ago from artist who already tried to create his profile twice:
> 
> <img alt="Screenshot 2024-07-16 at 12 59 37" width="600" src="https://private-user-images.githubusercontent.com/104380776/349057203-6dac1b4f-8f30-4fdc-9079-47782c83b7b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMzA0NzMsIm5iZiI6MTcyMTEzMDE3MywicGF0aCI6Ii8xMDQzODA3NzYvMzQ5MDU3MjAzLTZkYWMxYjRmLThmMzAtNGZkYy05MDc5LTQ3NzgyYzgzYjdiMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNlQxMTQyNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZmNlN2ZjMzAyN2JmNDQyNDMxN2EwNWJiM2M2MGQ0NzI5YmYxNGVjODA2ZWM0NjYzODRiNjc2NWQ1NzdiOWJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PyZDe19ZCwcuGusWmQj6YYzMr31jXEmmJZe8AKNXO30">
> What is the status of the profiles?

Due to `nft-storage` worker stop working, users can't upload any image to create profiles on the production env. https://github.com/kodadot/workers/issues/304

However, we have already replaced it with another available image service to fix this issue. The only thing that needs to be done is deployed the latest version to the production.  https://github.com/kodadot/nft-gallery/pull/10620  cc @vikiival

**Comment by Jarsen136** [comment]
deployed to production
