### ISSUE TITLE
Drop H-emitters

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#10718]
background?
avatar?

https://koda.art/ahp/drops/emitters

![image](https://github.com/user-attachments/assets/5b949d74-e3e9-4aa0-88a3-3f3de82216f1)

**Comment by preschian** [comment]
Oh hi 👋🏻
Miss seeing you around tho~

Quick fix: https://github.com/kodadot/nft-gallery/pull/10716. should be using `ImageMedia` component instead of `NuxtImg` alone. ref: https://github.com/kodadot/nft-gallery/blob/d7fc0010e4706fd199f78cf51f908ae5dee2124c/libs/ui/src/components/MediaItem/type/ImageMedia.vue#L20-L21
