### ISSUE TITLE
Status on drop is not loaded

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#10848]
### Context 

on turbulent drop, the minting status is not loaded

![photo_2024-08-16 21 18 45](https://github.com/user-attachments/assets/23a7c96e-193f-4b6d-a47b-7d2c8497b49f)

### Task

Make sure that it is properly loaded

**Comment by damskyftw** [comment]
Also, first 3 sec of loading show this 
<img width="810" alt="image" src="https://github.com/user-attachments/assets/0ab0863b-e776-497c-9406-a8dbf70fbe8c">

Is it how it was supposed to be?

If so, would be better to show 

<img width="480" alt="image" src="https://github.com/user-attachments/assets/8ba7117b-c3c3-498d-88f5-32aa12e85e01">

**Comment by preschian** [comment]
for the drops value I changed it to `10000000000000000` in cf-d1
for unlimited icon should be fixed in #10849 

fyi, in the basescan still show the number value: https://basescan.org/token/0x9789b13d485b124255f9dbf42aa7091aa22e87f8
![image](https://github.com/user-attachments/assets/9db67e4c-47aa-4763-b458-73d2ade24130)
