### ISSUE TITLE
Base: Error while minitng Quadz

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#10916]
Collection: https://kodadot.xyz/base/drops/quadz its a free collection on Base

I know its testing collection but i got an ugly error while trying to mint it

<img width="629" alt="Screenshot 2024-08-29 at 13 50 45" src="https://github.com/user-attachments/assets/85be0f5a-f874-494c-a6cd-648cc1d8c28d">

Video:

https://github.com/user-attachments/assets/a4c02129-397b-402c-9fbe-9d2b33ecf095

**Comment by hassnian** [comment]
cc @preschian

**Comment by preschian** [comment]
> cc @preschian

Thanks for mentioning it; after some checking, that drop should already be minted. Fixed in this PR:
- https://github.com/kodadot/nft-gallery/pull/10903
- [kodadot/private-workers@`394534d` (#213)](https://github.com/kodadot/private-workers/pull/213/commits/394534dc9561a6928d5045f43fc575eaf6ddef12)

Anyway, it seems like there is an inconsistent result within our contract. Need to double check. ref: https://github.com/kodadot/gensol/blob/ab0ac3daf5134c0d73e33815665d66630c0ab381/src/BaseGen.sol#L87-L94
