### ISSUE TITLE
App reports success on failed drop

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#11060]
### Context 

after - #11059 
I was shocked that app reported "minting successful"

![Screenshot 2024-09-30 at 12 04 58](https://github.com/user-attachments/assets/e8bc131d-bef3-48e0-b68d-47d280337e72)

### Fix

make sure that Error state is handled correctly as error 

### misc

maybe need design from @exezbcz

**Comment by vikiival** [comment]
cc any from @kodadot/internal-dev

**Comment by preschian** [comment]
seems like I put the toast in the wrong place
https://github.com/kodadot/nft-gallery/blob/3d2acdf04a44dd52b964f9d2ebc5820c6be9dabc/components/collection/drop/modal/shared/SuccessfulDrop.vue#L58-L73

**Comment by preschian** [comment]
> I was shocked that app reported "minting successful"

oohh, or maybe better should not render SuccessfulDrop.vue component instead

**Comment by vikiival** [comment]
> > I was shocked that app reported "minting successful"
> 
> oohh, or maybe better should not render SuccessfulDrop.vue component instead

![](https://trap.vik.ink/well)

**Comment by exezbcz** [comment]
yup, the error design toast template is here: 

<img width="600" alt="image" src="https://github.com/user-attachments/assets/5b3d52a8-6b10-4188-9c2a-2be18311c3f1">

https://www.figma.com/design/JXNtryaNYhY0XJNArzvPQx/Handoff?node-id=9705-14201&node-type=canvas&t=JcYs8Js306ghf8bU-11


we can put a copy like that: 

<img width="750" alt="image" src="https://github.com/user-attachments/assets/b22a0346-60c2-4778-9e05-b39521e928db">

"Minting of the drop has failed due to a technical issue. Please try again later"
