### ISSUE TITLE
Mass transfer feature

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#11072]
Once in a while, you want to send more NFTs to various addresses or transfer more NFTs to your second wallet. We don't have a way to do it!

Can we please think about having **a mass transfer** feature? 

Where it can be used
- giveaway and competitions
- when transferring more NFTs to another wallet

It will make things faster!

@kodadot/internal-dev, how hard is it to implement that?

**Comment by hassnian** [comment]
> @kodadot/internal-dev, how hard is it to implement that?

we already have something similar with mass listing, surely we can reuse some of that code

design is needed cc @exezbcz

**Comment by exezbcz** [comment]
sure, on it

**Comment by exezbcz** [comment]
# Design
available in: https://www.figma.com/design/JXNtryaNYhY0XJNArzvPQx/Handoff?node-id=2734-21138&node-type=canvas&t=oxF8FbhJCCMbV6sW-11


![image](https://github.com/user-attachments/assets/f9e9b3a8-b2a3-4cdf-9f23-9ce3bf7524f8)


shares a lot from transfer component, offer notification system, signing. Main part where the items are displayed in the modal is taken from the success modal when mass buying 

## Toast when selecting items
- here is a small change: new button for transfer alongside the list items button
![image](https://github.com/user-attachments/assets/da517e0f-1da0-40bf-825a-8a42d91c671a)
- they are both medium buttons, check the padding
- buttons follow button style guide 

## After clicking transfer
you are presented with a modal that has a list of items
- its the same list you have when mass buying 
- transfer to: 
	- same as a transfer modal for single nfts 
- don't forget about different states for the input
more here: 
![image](https://github.com/user-attachments/assets/a8d18589-c7b2-482c-b1c4-ba08a5263ed6)

https://www.figma.com/design/JXNtryaNYhY0XJNArzvPQx/Handoff?node-id=1287-18959&node-type=canvas&t=oxF8FbhJCCMbV6sW-11


## Sign and toast
- there won't a be congrats modal, there is not many converting actions after the transfer - it means it will be a progress toast, and then congrats 

![image](https://github.com/user-attachments/assets/33dd2ae8-6451-4107-8580-cb8223a98362)



same as offers just with different copy and in the congrats toas there is a link for the transaction



## other
- let me know if i have missed anything
- mass transfer is disabled on mobile since you cannot hover over the card and select it.
