### ISSUE TITLE
diff in `pnpm-lock.yaml`

### ISSUE THREAD

**Issue by hassnian** [kodadot/nft-gallery#11187]
### Is there an existing issue?

- [X] I have searched the existing issues

### What happened?

- go to main
- rm -rf node_modules pnpm-lock.yaml
- pnpm install

I see differences on my end , same with docker 

@kodadot/internal-dev anyone else ?

![CleanShot 2024-11-26 at 10 52 15@2x](https://github.com/user-attachments/assets/b0692405-db49-4d93-9579-0bd3a4b87ca7)

**Comment by preschian** [comment]
> * rm -rf node_modules pnpm-lock.yaml
> * pnpm install

It's expected if you remove the lock file first. It will bump sub-dependencies because they still satisfy the semver range version. You can get the same results even on popular repositories such as https://github.com/vuejs/core.

We can go with this as long as the app/build works fine. The thing is, not all packages use semver methodology. For example, sometimes minor/patch updates introduce breaking changes in some packages.

For a soft update, you can run these commands instead from your PR:

```bash
git checkout origin/main pnpm-lock.yaml
pnpm install
```
