### ISSUE TITLE
KodaDot in the wild list 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1171]
mybestlife has used kodadot for rmrk hackathon which we really like! 

https://discord.com/channels/840514076538830888/840514076538830894/909978638185807952
we are embracing this opportunity and create list of kodadot engines in wild 

Comment to this issue so we can list you, on README.md for example
- address url
- what's the goal of an instance
- who is it for

**Comment by Doinglifewell** [comment]
Thanks @yangwao I look forward to building along side KoDadot as we open up the capibilites of Darwinia.network I will ask @TopCodeBeast make contrbutuons shorty.

**Comment by TopCodeBeast** [comment]
I forked Kodadot Subquery from https://explorer.subquery.network/subquery/vikiival/magick and I changed only block height on code and I deployed.
At that time I can't fetch NFTs from that code.
I wondered and searched.
The result was a code mistake.
![image](https://user-images.githubusercontent.com/93806749/142085592-6ab8c4da-8b68-4cdb-a6ed-6fbd7a2626bd.png)

I found the error code on src/mappings/mappingHandlers.ts line 45
![image](https://user-images.githubusercontent.com/93806749/142085847-0b19b210-2423-410a-a38a-157122ab4cb7.png)

When it crate NFT id, there is no NFT id sometimes.
for example, if you don't create the collection and just create NFT, it doesn't have an id.
so I fixed the code like this.  just add nft.id   nft.id = getNftId(nft, remark.blockNumber)
![image](https://user-images.githubusercontent.com/93806749/142086078-7735f5b6-85b4-4848-9024-3f7d9c0097d9.png)


I wonder why this error did not happen on https://explorer.subquery.network/subquery/vikiival/magick and I think it was because you deployed many times and the data still exits while you delete and deploy new versions.

Thanks for reading my comment.
