### ISSUE TITLE
User based deny list

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1177]
Let's be honest, we don't like see [spammy feed](https://kodadot.xyz/rmrk/gallery?page=1071&search=&listed=true) and let's add user preferences add filter by
- artist address
- collection address

Make it shareable, so users can share deny lists between them easier. Like generating URL for sharing and load new sharing lists for them

###  Ref
- #942 #1160

**Comment by yangwao** [comment]
Adjusting flight plan 

https://twitter.com/KodaDot/status/1463090371886567433

**Comment by phillux** [comment]
Phil here, thanks for sharing.

A first-draft proposal should research and eventually implement something more like reddit moderation than opt-in user-generated deny lists, if we want to think long-term. 

In order to achieve this, there first needs to be a collectively agreed-upon position of what should be allowed and what should not be allowed on Kodadot. It should be noted that this is a challenge that should be well thought-out, as it is a "continuum problem" that must be shaped over time. For example, we know that images of real-world abuse should always be removed from the platform, and images of cute kittens should always be allowed. So where's the line in between?

Once we are able to establish a code of conduct we think would be appropriate for this community now and in the future, we can then begin to talk about methodologies such as councils, voting thresholds, voting periods, etc...

**Comment by yangwao** [comment]
> Phil here, thanks for sharing.

Welcome!

> A first-draft proposal should research and eventually implement something more like reddit moderation rather than opt-in user-generated deny lists, if we want to think long-term.

What's wrong with that? Happy to learn your perspective. Our long-term plan is we will encourage people to run forks of KodaDot instances in wild. #1171 
 
> In order to achieve this, there first needs to be a collectively agreed-upon position of what should be allowed and what should not be allowed on Kodadot. It should be noted that this is a challenge that should be well thought-out, as it is a "continuum problem" that must be shaped over time. For example, we know that images of real-world abuse should always be removed from the platform, and images of cute kittens should always be allowed. So where's the line in between?

Good Q! Right now I'm looking on that (hopefully media won't pick it up from here) like Aave and save pro, uniswap vs uni swap pro. At some point, we will need to be permissive and limit most of the stuff, however, like uniswap approach, encourage people run their frontends on their own costs of being sued for whatever happened there. Happy learn if there is better tactic, Because we as founder, caring responsibility what is served through "domain-name". 

> Once we are able to establish a code of conduct we think would be appropriate for this community now and in the future, we can then begin to talk about methodologies such as councils, voting thresholds, voting periods, etc...

I would happy to learn more. Is it something I'd invite you to our future Meta Hours (office hours) as host to openly discuss about it? It's quite hard stuff and we need to discuss more about this openly and inclusive. It would be recorded for long-tail latter opinions so allows anyone to react later in time and contribute.
