### ISSUE TITLE
Paused gifs by default / Ability to pause gifs 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#150]
Running gifs eating a lot of CPU power and do various perception disorders to an audience.

I would rather see play gifs when they are in item detail and being paused on gallery view.

Save the planet on resources.

Put $, put if it will be robust, may extend to $$

**Comment by JKrupinski** [comment]
@yangwao @vikiival  I want to work on this feature but there is no information in nft object if it's a gif. Do you know if there is any way to add it to nft data? Without such info it will be hard to do.

Pausing gifs probably can be done by using freezeframe library https://github.com/ctrl-freaks/freezeframe.js/
however there can be some issues because of lazyloading

**Comment by JKrupinski** [comment]
I think you can close this one

**Comment by yangwao** [comment]
Oh though PR should automatically close issue on merge!
