### ISSUE TITLE
(JS-0693) Use interpolation expressions instead of the `v-html` attribute

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1543]
## Description
It is recommended to use interpolation expressions instead of using `v-html` as it prevents injection attacks like XSS.

## Occurrences
There are 5 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/kodadot/nft-gallery/issue/JS-0693/occurrences/](https://deepsource.io/gh/kodadot/nft-gallery/issue/JS-0693/occurrences/)

**Comment by kkukelka** [comment]
@yangwao isn't this only relevant in relation to user-generated content? static texts like faqs shouldn't be prone to injections in that way

**Comment by LatinSoul** [comment]
Indeed, since it's not user-generated content, there shouldn't be any risk, although avoiding it when possible is considered best practice. That said, it seems that there is a gain in speed when using interpolation vs v-html as per what I've been reading on vue.js forum.  I'll do the changes and submit the PR.
