### ISSUE TITLE
Floating helper for nontech users/total newcomers

### ISSUE THREAD

**Issue by damskyftw** [kodadot/nft-gallery#1637]
### Is your feature request related to a problem?

@XyloDrone said
> Please tag me in any new PRs/issues being opened that have any relation to UX/UI so I can keep adding these to the mind map accordingly + providing designs so that devs don’t have to bother with this, as it is my duty to sort out UX/UI so you can focus on what you do best. 

What i see as a problem when thinking as total newcomer - #1445 the biggest problem is that those people don't know half of the words displayed on the page. To quickly solve this problem, i was thinking to implement a "floating" version of the page, which would basicly transform the page into floating mode and your cursor would work as automatic hint once you move the cursor on some words.

### Describe the solution you would like

 With this mode you can move your cursor throughout the page and small windows with easy explanations would pop up depending on where would you move your cursor.
It would certainly help total newcomers to find out quickly what are these buzzwords. I've done a little explanation illustration how i'd imagine this. It's just an idea, but definitely it is faster than clicking all the categories and finding out one by one.

### Describe alternatives you have considered

Only alternative that comes to my mind is to make the page so simple, nobody will have to think about certain buzzwords. Like i said, this idea is solely for complete newcomers who don't even know what an nft is and somehow made their way to KodaDot.

### Screeenshots

This is purely to show what i was thinking, the final solution can be different or worked on.
I know there's redesign on the way and that's why we could consider implementing this, share your thoughts please!

Once clicking on "floating helper" the page would turn into this mode and would like somewhat like this:

![Pasted image 20211221134929](https://user-images.githubusercontent.com/92786519/147747377-6fe57a32-84f4-4f04-b850-3fa66f40ddad.png)

**Comment by cryptodamsky** [comment]
As i look further at the Screenshot i posted, the explanation of categories/buzzwords would have to be way simpler and understandable without knowledge of crypto-glossary, as most probably only total newcomers would use this feature.

**Comment by XyloDrone** [comment]
I think this would be a good addition in some places (if it's everywhere it might be a bit much, so perhaps we can decide which elements are not straight forward). 

What if we add an "i" to certain sections?

**Comment by roiLeo** [comment]
Feature wise it could be something like:
- a feature ["tour" guide](https://twitter.com/okta/status/1471533922509074440)
- or [feature Discovery](https://material.io/archive/guidelines/growth-communications/feature-discovery.html)

**Comment by XyloDrone** [comment]
I vote for "tour guide" and we can structure our FAQ as feature discovery?

**Comment by cryptodamsky** [comment]
I see this is little bit on hold for now, but as part of onboarding experience, like i said i'll have plenty of materials what is understandable for newcomer and what not. But, since there is lot of stuff changing, for now i'd implement a small "i" or once hovered with cursor over these, a little explanation wouldn't be bad:

I can see explanations implemented while clicking on create, that is brilliant!!

![help1](https://user-images.githubusercontent.com/92786519/150792935-34ac46a7-ddb0-4ba1-8e70-d56218c3f59c.png)

- would add "i" or something, to explain what is NFSW content to the red frame

![hep2](https://user-images.githubusercontent.com/92786519/150792937-468f676a-cc15-43d1-bf8b-b5e25348e133.png)

- here i think it could have some hover frame explanation

![help3](https://user-images.githubusercontent.com/92786519/150792916-5a1f20c1-25a1-4353-b820-ec160a0b1443.png)

- same here

![help 3](https://user-images.githubusercontent.com/92786519/150792938-e87ac265-1016-4cae-9643-3e7e469179cf.png)

----

It's a little painful to find out one by one what these mean. Since these icons are not that famous ye or not mainstream, it'd deserve some popup information when moving cursor onto them.

**Comment by yangwao** [comment]
@exezbcz is there anything we can recycle to new design?

**Comment by exezbcz** [comment]
> @exezbcz is there anything we can recycle to new design?

not really, since we've changed it to more useful icons and naming.
- for example gift is now transfer and qr and link is under share section.
