### ISSUE TITLE
can we remove these warnings during build

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1677]
would be nice to mitigate warnings 
while yarn dev or yarn generate
![image](https://user-images.githubusercontent.com/5887929/147939494-84fdd8fc-f57b-48f4-8688-4f2f1882bd51.png)

**Comment by kkukelka** [comment]
@yangwao
there are 2 mitigation strategies here:
1. rename fragments in unique folder
2. disable this warning by invoking disableFragmentWarnings 
which do you prefer?

**Comment by yangwao** [comment]
But wait, is that issue with our queries? Removing warning isn't the best way tho as warning is there for reason? 😄
cc @vikiival maybe to shot his insight

**Comment by vikiival** [comment]
disabling warning is not best, but acceptable approach.
 
 **What is Fragment?** 
 Fragment is a reusable piece of grapghQL query, so instead of querying `name, metadata, max, you can write `...collection`
 
 The best approach would be to create reusable fragment (eg. `baseCollection`) and then extend fragment with baseCollection and other data

**Comment by kkukelka** [comment]
It doesn't effect our queries since we explicitly import the corresponding fragment correctly.
The library just checks globally if there are multiple fragments with the same name. This warning however doesn't imply that something is broken. It's just hinting at the fact that we **could** be importing the wrong fragment or even two fragments with the same name (which in fact would break the query).

I can of course implement it via extensions like @vikiival suggested

**Comment by yangwao** [comment]
> I can of course implement it via extensions like @vikiival suggested

Yup, rather try to fix warning by naturally solve the issue :)

**Comment by kkukelka** [comment]
@vikiival sadly it looks like we cannot just extend fragments of fragments like with classes and interfaces. i therefore split up the "extended" one into separate fragments. and then we just import them both like described here https://www.apollographql.com/docs/react/data/fragments/#creating-colocated-fragments

**Comment by vikiival** [comment]
["Alexa play summertime sadness"](https://open.spotify.com/track/3BJe4B8zGnqEdQPMvfVjuS?si=epUjBhVSTs2orN_GVzbbJA)
