### ISSUE TITLE
Serverless affiliate/referral link engine

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1722]
Make function with KV worker to make referral links and account some referall fee for people and figure out incentives scheme to spread the word about KodaDot

We can expand on this more

### Incentivize goals
- bring more people
- more artists
- more collectors

### Qualification
- Log In with Twitter (have a minimal amount of Twitter, 20?) ?
- Have a minimal amount of $KSM on address (verify their KSM address)

### Prevention
- artificial audience
- spammy behaviour
- gaming the system

### Ref
- Might be part of $koda
- Sign message - https://cloudflare-ipfs.com/ipns/dotapps.io/#/signing
- Verify message - https://cloudflare-ipfs.com/ipns/dotapps.io/#/signing/verify

**Comment by atharva3010** [comment]
@yangwao let's do this.

I think the easiest route to go about this would be for users to submit their wallet address as it is a unique key and we don't have to worry about the authentication of the user as the user will receive a payout in their wallet only.

**Comment by yangwao** [comment]
@Franks ideation 💡

![Screenshot_2022-05-08-10-30-58-50_572064f74bd5f9fa804b05334aa4f912.jpg](https://user-images.githubusercontent.com/5887929/167288169-3391b40a-96db-4f3f-832e-8f4d0a3348ff.jpg)

**Comment by Skylla54** [comment]
# Hoi

Yeap, thats me 🐼

### 💡 The idea is based on two sources
+ [Vue Docs](https://vuejs.org/guide/extras/web-components.html#building-custom-elements-with-vue)
+ Eric, he pops up in my [YT-Feed](https://www.youtube.com/watch?v=SoPo7bnhbqA) quite often, give him a click, its free.

### 💻 Some links after a quick google search 
+ [WebCompents.org - SmartCard](https://www.webcomponents.org/element/HTMLElements/smart-card)
+ [Medium Article about Web Components Libaries](https://blog.bitsrc.io/9-web-component-ui-libraries-you-should-know-in-2019-9d4476c3f103)
+ [My favorite based on Look🦖](https://wiredjs.com/)
+ [Another example](https://www.webcomponents.org/element/wise-shopping-cart)
+ [Another video](https://www.youtube.com/watch?v=w2Woat-LxCM)

### 🦥Quick refresher
A Webcomponent is created thruh the browsers [ShadowRoot WebAPI](https://developer.mozilla.org/en-US/docs/Web/API/ShadowRoot) . 
Its not affected by global styling and can live in his own scope, that so called shadowDom. 
The main thought of it is to share components easily between developers but didn't get widespread adoption, as they hoped it would. 
Most likely because of appearing of scoped styles in diffrent FrontendFramewokrs/Libaries.

**Comment by yangwao** [comment]
Apply the same PayPal strategy, refer friends, and both of you get $10; it's an easy start. 

## Condition to receive referral aware could be  
- your friend is a unique artist and mints at least 6 pictures (want to optimize for quality ofc)

## Technical
- for a start, cap it for the first 50 friends 
- using cookies should be enough
- only trigger referral per one web3 address (doesn't mind if the address has minted already on RMRK,BSX or Astar, leverage ss58)
- for the check, show referred field at first minting only to confirm who your referral is for user
- rewards could be flexible in multicurrency, and for a start, can we use $KSM? 
- have a separate domain as ppl tend to spam with that everywhere, and we don't want to see K domain blacklisted (will figure out something short)
- include link shortener
- personalized links are limited now for those 
  - first 10 	
  - who have referred at least 30 friends


### Later nice to have integrations
- Like Gleam, having followed on Twitter &c

## Copy & Design
### Referee
- Bulky UI 
	- which will generate & show uuid-v4 referral link for user with the custom domain we'll set
	- copy to clipboard
	- share to socials / send to a friend	
	- show table 
		- total amount of referrals
		- web3 address linked to profile
		- link to NFTs minted
		- amount of nfts minted per web3 address (show how much items needs to be minted)
	- the amount of payout 

- Write the conditions of referral campaign
- submit email for referral campaign as it will be gradually rolled for oldest & most active users first

## Quick Math
hypothesis
we've got 30 power users, which will referer each 30; it will bring us 900 new users minting, approximately close to 5400 new NFTs  

## Research

@cryptodamsky can research some good referral campaigns also anyone else. I want to keep it KISS, and it just works; we can tune it later ofc:)

**Comment by yangwao** [comment]
Continue to condensed Referral engine into 
- #4635 


> The idea is based on two sources

I guess something we did in the past yet due x-frame and security we turned it off, hence it's still possibility to have! 
This can be made as royalty in web stuff.

@FrankBevr  let's create a new issue for this would be nice to get funded

OR can be as a separate track in our grants program
- https://github.com/kodadot/nft-gallery/discussions/3448

I welcome great ideas!
