### ISSUE TITLE
Recommend dimension for picture for best experience 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1911]
I guess we should add a simple mint way to recommend users for best experience what ratio dimension picture should have

### Case
It's cutted from top and bottom as picture is more narrow

https://beta.kodadot.xyz/rmrk/detail/11015267-0E76E3AC15B4C1FA1E-METAHOURS-META_HOURS_3_1-0000000000000001

vs 
![image](https://user-images.githubusercontent.com/5887929/149921081-aaa561cd-95f6-45d5-9f6a-d052773acbaa.png)

**Comment by vikiival** [comment]
![Screenshot 2024-07-31 at 15 42 58](https://github.com/user-attachments/assets/4f318dec-7543-4f71-a51c-efdc8d871d6c)
![Screenshot 2024-07-31 at 15 42 47](https://github.com/user-attachments/assets/426f44cb-5972-422c-a946-291cb0d36274)

This is due to reason we are supporting squarinsh thingies, user can see full pic in fullscreen mode
