### ISSUE TITLE
Bump various dependencies 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1999]
Check if everything works in-app tho or when it could potentially harm previous application workflow or break something

```
idb-keyval | ^5.1.5 -> ^6.1.0
sass-loader | ^10.2 -> ^12.4
mingo | ^4.4.1 -> ^5.0.0
css-loader | 4.3.0 -> 6.5.1
ansi-regex | ^5.0.1 -> ^6.0.1
@vue/cli-plugin-babel | ^3.12.1 -> ^4.5.15
@types/webpack | ^4.41.32 -> ^5.28.0
@intlify/vue-i18n-loader | ^1.1.0 -> ^4.1.0
```

### Ref
- https://github.com/kodadot/nft-gallery/pull/1995
- https://github.com/kodadot/nft-gallery/pull/1998
- https://github.com/kodadot/nft-gallery/pull/1997
- https://github.com/kodadot/nft-gallery/pull/1993
- https://github.com/kodadot/nft-gallery/pull/1992
- https://github.com/kodadot/nft-gallery/pull/1991
- https://github.com/kodadot/nft-gallery/pull/1990
- https://github.com/kodadot/nft-gallery/pull/1989

**Comment by kkukelka** [comment]
On it.

**Comment by kkukelka** [comment]
just for reference

### @types/webpack, sass-loader, css-loader
Vue 2.6.2 only goes together with webpack 4 -> latest we can go is 4.41.32

-> Css-loader ^6.0.0 requires webpack 5 -> latest we can go is 5.2.7

-> sass-loader ^11.0.0 requires webpack 5 -> latest we can go is 10.2

### @intlify/vue-i18n-loader 
We use vue-i18n 8.27.0 -> The version for Vue I18n v8.x is now in @intlify/vue-i18n-loader v1.x! 

### ansi-regex
We aren’t using this anymore afaik

### @intlify/vue-i18n-loader
I’ll make a separate issue regarding this package, because I believe during nuxt migration we didn’ change to @nuxt/i18n even though we have it as a dependency. 
Config still seems to rely on `import VueI18n, { LocaleMessages } from 'vue-i18n’`

**Comment by yangwao** [comment]
> just for reference
> 
> ### @types/webpack, sass-loader, css-loader
> Vue 2.6.2 only goes together with webpack 4 -> latest we can go is 4.41.32
> Css-loader ^6.0.0 requires webpack 5 -> latest we can go is 5.2.7
> sass-loader ^11.0.0 requires webpack 5 -> latest we can go is 10.2

Let's try to update it to latest at least :)

>  I believe during nuxt migration we didn't change to @nuxt/i18n even though we have it as a dependency.

yes, that's what triggered me to investigate into cleanup that we are installing packages which aren't used or we can use Nuxt versions
