### ISSUE TITLE
Check why recent NFT on sale doesn't load

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2350]
doesn't work either on kodadot.xyz nor beta.kodadot.xyz so must be in `main` ?

![image](https://user-images.githubusercontent.com/5887929/153855391-0f9aa84d-0c15-4cda-8a28-101b8026ffb5.png)

**Comment by zhyd1997** [comment]
It works now, I think

**Comment by yangwao** [comment]
> Maybe a failed entity or a burned nft? ![Capture d’écran 2022-02-14 à 3 29 18 PM](https://user-images.githubusercontent.com/9987732/153883269-33a90887-cebd-408b-b018-7b78c30f0070.png)

highly possible latter one, do we handle it?

**Comment by roiLeo** [comment]
This one was not loading because it has `meta: null`
![Capture d’écran 2022-02-15 à 4 44 51 PM](https://user-images.githubusercontent.com/9987732/154096975-2202fe29-91df-4e5f-a026-5cf4f43d7794.png)

Link for future reference:
`/rmrk/gallery/10989541-c095ca1430a05e7d6b-7-UTOPIA_29-0000000000000029`

**Comment by zhyd1997** [comment]
Why the `meta` could be `nullable`?
(Not working on this issue, just wondering why)

**Comment by roiLeo** [comment]
> Why the `meta` could be `nullable`? (Not working on this issue, just wondering why)

meta field is refering to [MetadataEntity](https://github.com/kodadot/rubick/blob/3a70f5d63e7e595dfeda76accc2d767898a3ba61/schema.graphql#L53), I don't know why it can be null sometimes

**Comment by yangwao** [comment]
meanwhile solved
and seems broken again 🫣
continue to #2668
