### ISSUE TITLE
burned nfts showing up in gallery

### ISSUE THREAD

**Issue by petersopko** [kodadot/nft-gallery#2382]
### What happened?

When loading https://kodadot.xyz/rmrk/gallery I can still see NFTs which are burned (such as the cute little cat below).
Here's the [link](https://kodadot.xyz/rmrk/gallery/11441876-be4a994fc285785166-BIRMAN%20CAT%20#1-BIRMAN_CAT_1-0000000000000001).
![image](https://user-images.githubusercontent.com/73316633/154436239-758e9311-d287-4e69-a98f-4d5299cfa22b.png)

Video showing the behaviour:

https://user-images.githubusercontent.com/73316633/154436587-b62b8874-2b2c-4846-8f30-812448990fe5.mp4

### Please reproduce in steps

check the link / video / gallery. might not be there later. test at burned nft.

### Expected Behavior

I've expected burned nfts to dissapear from main gallery page.

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### Are you logged in?

No

### At which address did you encounter bug?

nft.kodadot.xyz / kodadot.xyz

### Screenshots

uploaded above.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yangwao** [comment]
I would handle to NFT item detail component at first that users are looking at burned NFT somehow :)

**Comment by roiLeo** [comment]
Nft is not burned, this happened because the nft id wasn't well parsed in the graphql query

#### Current (`{ nFTEntity: null }`)
ID: `11441876-be4a994fc285785166-BIRMAN CAT`
![Capture d’écran 2022-02-17 à 2 30 38 PM](https://user-images.githubusercontent.com/9987732/154491963-472f1a67-4419-4cb4-a1cb-89ce9a5fd21e.png)

#### Working ID
ID: `11441876-be4a994fc285785166-BIRMAN CAT #1-BIRMAN_CAT_1-0000000000000001`
![Capture d’écran 2022-02-17 à 2 30 59 PM](https://user-images.githubusercontent.com/9987732/154492206-cbaeebd9-24fb-478b-8a2c-b37654dabe73.png)
