### ISSUE TITLE
Social media previews

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2388]
Curious it works on beta but doesn't on production,why is that?

![image](https://user-images.githubusercontent.com/5887929/154557356-c0351c16-9daa-4fdc-86ef-7700f809521c.png)

**Comment by newraina** [comment]
@yangwao  I used [Facebook Sharing Debugger](https://developers.facebook.com/tools/debug/) to find out what scraper sees for our URL: [beta.kodadot.xyz](https://developers.facebook.com/tools/debug/echo/?q=https%3A%2F%2Fbeta.kodadot.xyz%2Frmrk%2Fgallery%2F11664198-4466b2edfa4d261069-POLKAORIGINS-HUNTER-0000000000000006) | [kodadot.xyz](https://developers.facebook.com/tools/debug/echo/?q=https%3A%2F%2Fkodadot.xyz%2Frmrk%2Fgallery%2F11664198-4466b2edfa4d261069-POLKAORIGINS-HUNTER-0000000000000006)

From the result, we know that the beta version has been prerendered, but the prod version has not, which results in the different value of `og:image`. That's why social media previews are different.

Maybe we just forgot to set up prerendering for the prod version?

Refs:
- https://docs.netlify.com/site-deploys/post-processing/prerendering/#set-up-prerendering
- https://answers.netlify.com/t/support-guide-understanding-and-debugging-prerendering/150

**Comment by yangwao** [comment]
> @yangwao I used [Facebook Sharing Debugger](https://developers.facebook.com/tools/debug/) to find out what scraper sees for our URL: [beta.kodadot.xyz](https://developers.facebook.com/tools/debug/echo/?q=https%3A%2F%2Fbeta.kodadot.xyz%2Frmrk%2Fgallery%2F11664198-4466b2edfa4d261069-POLKAORIGINS-HUNTER-0000000000000006) | [kodadot.xyz](https://developers.facebook.com/tools/debug/echo/?q=https%3A%2F%2Fkodadot.xyz%2Frmrk%2Fgallery%2F11664198-4466b2edfa4d261069-POLKAORIGINS-HUNTER-0000000000000006)
> 
> From the result, I know that the beta version has been prerendered, but the prod version has not, which results in the different value of `og:image`. That's why social media previews are different.
> 
> Maybe we just forgot to set up prerendering in Netlify for the prod version?
> 
> Refs:
> 
> * [docs.netlify.com/site-deploys/post-processing/prerendering/#set-up-prerendering](https://docs.netlify.com/site-deploys/post-processing/prerendering/#set-up-prerendering)
> * [answers.netlify.com/t/support-guide-understanding-and-debugging-prerendering/150](https://answers.netlify.com/t/support-guide-understanding-and-debugging-prerendering/150)

Well, we running production on Cloudflare pages, not sure if they have prerendering? Other than that, I guess pretender doesn't have impact unless you are SPA which we are not much anymore. but let see on other opinion out there

**Comment by roiLeo** [comment]
ref #3038

**Comment by yangwao** [comment]
Solved partially, we are usign ssr and prerender workers

Continue in 
- #5567
