### ISSUE TITLE
Sometimes it won't load identity of an address

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2468]
Hey. I don't think this will correct anything, Twitter link is working well, thing is that sometimes it won't load identity of an address

_Originally posted by @roiLeo in https://github.com/kodadot/nft-gallery/pull/2429#pullrequestreview-890708515_

Continue from https://github.com/kodadot/nft-gallery/issues/1416

**Comment by preschian** [comment]
I just found out how to reproduce this issue:
1. Clear `IndexedDB` from developer tools.
2. Reload the page.

I still don't know what the root cause is. It seems that the profile page didn't re-fetch and store user data.

| Expected | Unexpected |
| ------------- | ------------- |
| <img width="2032" alt="Screen Shot 2022-03-12 at 12 02 13 PM" src="https://user-images.githubusercontent.com/734428/158004957-996c51e1-92d1-45fa-bb9a-ae241a6d2f9f.png"> | <img width="2032" alt="Screen Shot 2022-03-12 at 12 02 31 PM" src="https://user-images.githubusercontent.com/734428/158004964-a1c4240e-1c0b-4df8-97c1-6a69f316a81c.png"> |
