### ISSUE TITLE
Social previews og:image work on beta, but not at production

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2759]
It's quite weird as we should have almost the same deployment :)
Maybe services processing this kind of stuff are down bad?

https://beta.kodadot.xyz/rmrk/gallery/12018704-900D19DC7D3C444E4C-KSMBOT-KUSAMA_BOT_100-0000000000000103
vs
https://kodadot.xyz/rmrk/gallery/12018704-900D19DC7D3C444E4C-KSMBOT-KUSAMA_BOT_100-0000000000000103

<img width="842" alt="image" src="https://user-images.githubusercontent.com/5887929/161514053-eead2c66-8b34-45fa-84e4-5303d37277f4.png">

**Comment by kkukelka** [comment]
@yangwao is beta running on netlify?

**Comment by yangwao** [comment]
> @yangwao is beta running on netlify?

yes. but I guess it's Vercel service which does this render, not Netlify.

**Comment by preschian** [comment]
I will try to experiment with this later. seems like Cloudflare does not support pre-render. the idea is to serve and adjust `og:image` gallery detail with Cloudflare workers. not sure is it possible or not 🙈

current:
`kodadot.xyz/gallery/* -> render`
use workers:
`kodadot.xyz/gallery/* -> workers -> render`

related issues:
- https://github.com/kodadot/nft-gallery/issues/2136
- https://github.com/kodadot/nft-gallery/issues/2388

**Comment by preschian** [comment]
yaps, possible with Cloudflare Workers

POC Results:
&nbsp; | before | after
--- | --- | ---
screenshot | <img width="1008" alt="Screen Shot 2022-04-09 at 9 41 55 PM" src="https://user-images.githubusercontent.com/734428/162579018-c86db3d6-9c5f-42aa-86aa-5b14f85e8988.png"> | <img width="1009" alt="Screen Shot 2022-04-09 at 9 42 49 PM" src="https://user-images.githubusercontent.com/734428/162579033-8557ce62-8db9-4fc5-88c6-d41428e04c0a.png">
URL | https://kodadot.xyz/rmrk/gallery/12176545-4466b2edfa4d261069-POLKAORIGINS-RAV3N-0000000000000008 | https://twilight-forest-de98.preschian-cdn.workers.dev/rmrk/gallery/12176545-4466b2edfa4d261069-POLKAORIGINS-RAV3N-0000000000000008

source code: https://gist.github.com/preschian/c979ba5ccf1c3c44d4898777676f2d7e

I don't have a domain for testing, need to apply route config in the Cloudflare dashboard
- docs: https://developers.cloudflare.com/workers/platform/routes/#matching-behavior
- route: `*kodadot.xyz/rmrk/gallery/*`
<img width="1299" alt="Screen Shot 2022-04-09 at 9 47 32 PM" src="https://user-images.githubusercontent.com/734428/162579214-42207b06-5a4e-49e1-a501-2cc66d227eb5.png">

**Comment by yangwao** [comment]
Ooh, amazing 😍 I can give you access to our CF, ping me on Discord! :)

**Comment by vikiival** [comment]
> But I guess we should use CF images instead Pinata for faster access times.

Yup you just need to ask another CF worker to give you id for the image

**Comment by XyloDrone** [comment]
Hey peeps, any chance we can change the logo to the one on the site, as such?
![Screenshot 2022-04-11 at 11 23 29](https://user-images.githubusercontent.com/84407059/162721029-d1b71825-9436-4ccf-8495-44b47b2004c8.png)

Here is the SVG file: 
![Koda _pink](https://user-images.githubusercontent.com/84407059/162721154-0a22cdca-e33b-4eff-95e6-76b05df31842.svg)

**Comment by kkukelka** [comment]
> Hey peeps, any chance we can change the logo to the one on the site, as such? ![Screenshot 2022-04-11 at 11 23 29](https://user-images.githubusercontent.com/84407059/162721029-d1b71825-9436-4ccf-8495-44b47b2004c8.png)
> 
> Here is the SVG file: ![Koda _pink](https://user-images.githubusercontent.com/84407059/162721154-0a22cdca-e33b-4eff-95e6-76b05df31842.svg)

ill do this later today https://github.com/kodadot/nft-gallery/issues/2818

**Comment by preschian** [comment]
> Ooh, amazing 😍 I can give you access to our CF, ping me on Discord! :)
> 
> But I guess we should use CF images instead Pinata for faster access times.
> 
> I mean Vercel should do this preprocessing so what's your worker actually does?
> 
> 📟 @vikiival

noted, will check cf images instead of pinata

I think the vercel is for "image generator"

the worker modifies HTML before returning to the user
before:
1. browser receive this tag `<meta property="og:image" content="https://kodadot.xyz/kodadot_card_root.png">`

after:
1. browser receive this tag `<meta property="og:image" content="https://vercel.app/image.png">`

**Comment by yangwao** [comment]
handover access to @preschian so will see when we can see new previews! :)

**Comment by preschian** [comment]
updates:
since yesterday I assigned this route `*kodadot.xyz/rmrk/gallery/*` to the CF-workers
there is still some item detail missing, will add missing detail in this https://github.com/kodadot/nft-gallery/issues/2849

notes:
it seems some old items still not fully working because need time to resolve cache from the CF side

telegram | discord | twitter
--- | --- | ---
<img width="378" alt="Screen Shot 2022-04-14 at 12 45 29 PM" src="https://user-images.githubusercontent.com/734428/163321931-b958ec17-b50b-4532-88ab-6f8f50c1dae9.png"> | <img width="810" alt="Screen Shot 2022-04-14 at 12 45 43 PM" src="https://user-images.githubusercontent.com/734428/163321964-ee61bb02-8c35-4884-b3c1-9bd5bbca4560.png"> | <img width="530" alt="Screen Shot 2022-04-14 at 12 47 28 PM" src="https://user-images.githubusercontent.com/734428/163321985-48bb0ce7-46fd-44e8-8698-be7d0fa05529.png">

**Comment by preschian** [comment]
I found another solution by using prerender.io on cf-workers. easier than the current script running on production. tested here https://github.com/preschian/prerender-cf-workers

results:
- https://kodadot.preschian.xyz/rmrk/gallery/11238234-e0b9bdcc456a36497a-RMRKBNNRS-ARK_PROBABLY_NOTHING-0000000000000231
- https://kodadot.preschian.xyz/bsx/gallery/3308315261-1
- https://kodadot.preschian.xyz/moonsama/collection/0xe4edcaaea73684b310fc206405ee80abcec73ee0

| rmrk | basilisk | moonsama |
| --- | --- | --- |
| ![www opengraph xyz_url_https%3A%2F%2Fkodadot preschian xyz%2Frmrk%2Fgallery%2F11238234-e0b9bdcc456a36497a-RMRKBNNRS-ARK_PROBABLY_NOTHING-0000000000000231](https://user-images.githubusercontent.com/734428/180705443-a14c3733-9821-4155-a7e2-93ea58b49989.png) | ![www opengraph xyz_url_https%3A%2F%2Fkodadot preschian xyz%2Fbsx%2Fgallery%2F3308315261-1](https://user-images.githubusercontent.com/734428/180705480-5bc9a5b1-7604-490b-b0d5-5e0e19bb49c1.png) | ![www opengraph xyz_url_https%3A%2F%2Fkodadot preschian xyz%2Fbsx%2Fgallery%2F3308315261-1 (1)](https://user-images.githubusercontent.com/734428/180705527-3bbc5344-10ea-4f8c-98ea-cc351306d1b4.png) |

what do you guys think?

**Comment by roiLeo** [comment]
I find pricing a bit expensive for what it's supposed to do.

What's the current issue with vercel prerender? Any idea why it's not working well on kodadot.xyz but works on beta?

**Comment by preschian** [comment]
> I find pricing a bit expensive for what it's supposed to do.
> 
> What's the current issue with vercel prerender? Any idea why it's not working well on kodadot.xyz but works on beta?

did you mean vercel this one https://github.com/AndreyGrin/og-image?
no issue with that one. I think that one has a different purpose, vercel returns a dynamic image from the URL, not doing prerender

the difference between beta and main domain is `beta.kodadot.xyz` served by Netlify. On Netlify already built-in support for prerendering https://docs.netlify.com/site-deploys/post-processing/prerendering/

main domain `kodadot.xyz` served by Cloudflare pages. For now, there is no built-in support for prerendering

alternative solution:
- serve main domain to use Netlify instead of Cloudflare Pages (seems like the easiest)
- change render method from SPA to SSR (hardest)
- use prerender.io, I want to avoid the pricing also, maybe enough for us using the free tier
- current production, [gist code](https://gist.github.com/preschian/6c929effbfae7d97f60f8964aebf522a)
  - pros: cheap
  - cons: a little bit complex when kodadot support another chain

**Comment by roiLeo** [comment]
> no issue with that one. I think that one has a different purpose, vercel returns a dynamic image from the URL, not doing prerender
> 
> main domain `kodadot.xyz` served by Cloudflare pages. For now, there is no built-in support for prerendering

If I understand we serve production with Cloudflare and beta/preview with Netlify, do you know why?



**alternative solution:**
 
>  serve main domain to use Netlify instead of Cloudflare Pages (seems like the easiest)

I think that was the solution we had before cloudflare

>  change render method from SPA to SSR (hardest)

I'm pretty sure this one will break stuff and we'll need more work to convert to SSR.
That was the initial goal with the Nuxt migration.

> current production, [gist code](https://gist.github.com/preschian/6c929effbfae7d97f60f8964aebf522a)

I find this solution a bit far-fetched

**Comment by preschian** [comment]
> If I understand we serve production with Cloudflare and beta/preview with Netlify, do you know why?

I don't know the reason, I think when I first landed in kodadot already using that flow
maybe the founder has some reason for that cc @yangwao 

> I find this solution a bit far-fetched

agree, I think the easiest solution so far to tackle this issue:
- serve primary domain use Netlify, or
- still in Cloudflare pages, but add prerender.io in workers

> **Note**
> Even though we are using nuxt, our rendering method still uses [static](https://github.com/kodadot/nft-gallery/blob/main/nuxt.config.js#L37). that means similar to SPA/Client Side Rendering. that's why we still need a kind of prerendering method

**Comment by preschian** [comment]
cc @yangwao @vikiival @roiLeo 
need your approval to use prerender.io through workers. I think we need to use it until we find a better alternative
source code: https://github.com/preschian/prerender-cf-workers

**Comment by roiLeo** [comment]
> need your approval to use prerender.io through workers. I think we need to use it until we find a better alternative source code: https://github.com/preschian/prerender-cf-workers

I tried to test it and it didn't work on `https://kodadot.preschian.xyz/bsx/collection/3813476019`

![Capture d’écran 2022-10-11 à 12 52 40 PM](https://user-images.githubusercontent.com/9987732/195071916-f5c19fa3-46da-4478-9cfb-5e7104607ec5.png)
![Capture d’écran 2022-10-11 à 12 52 26 PM](https://user-images.githubusercontent.com/9987732/195071926-8cab9f41-5e96-45d0-a033-637bf96072dc.png)


1,000 / month for free plan is not much
I think the other plan are a bit too expensive... can't we fix current implementation?

**Comment by preschian** [comment]
> I tried to test it and it didn't work on https://kodadot.preschian.xyz/bsx/collection/3813476019

better test it with facebook debugger https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fkodadot.preschian.xyz%2Fbsx%2Fcollection%2F3813476019
opengraph.xyz has a custom user-agent, so need to update it again https://github.com/preschian/prerender-cf-workers/blob/main/src/constant.ts#L38

apart from that, prerender.io will take some time for the first page

> can't we fix current implementation?

need to find a better solution, I think. because with the current script it will be harder to maintain if we support more another chain ref: https://github.com/kodadot/nft-gallery/issues/2759#issuecomment-1193957133

**Comment by roiLeo** [comment]
> alternative solution:
> - serve main domain to use Netlify instead of Cloudflare Pages (seems like the easiest)

This could be doable, why did we change to cloudflare at some point? (can't find answer in repo issues)

> - change render method from SPA to SSR (hardest)

We would benefit from this, I think that's the goal (in near future #4040 related) to migrate to SSR

> better test it with facebook debugger https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fkodadot.preschian.xyz%2Fbsx%2Fcollection%2F3813476019 opengraph.xyz has a custom user-agent, so need to update it again https://github.com/preschian/prerender-cf-workers/blob/main/src/constant.ts#L38
> 
> apart from that, the downside with prerender.io it will take some time for the first time page

- ok with fb sharing debugger
- don't work with twitter debugger
- don't work on discord

**Comment by preschian** [comment]
> This could be doable, why did we change to cloudflare at some point? (can't find answer in repo issues)

maybe since the beginning already used Cloudflare pages for production. I think @yangwao and @vikiival are the people who can answer this question

**Comment by vikiival** [comment]
We have a ton of minutes on Cloudflare for deployment. More CDNs on Cloudflare.

Should be logged somewhere in Metahours.

or we can fix kodadot/bao#11

**Comment by preschian** [comment]
> ok with fb sharing debugger
> don't work with twitter debugger
> don't work on discord

currently, a script on https://github.com/preschian/prerender-cf-workers quota for prerender.io will be counted and triggered when the user-agent is from social media. So, the link will not work like this screenshot for the first time. but after that, the open graph media will show up. I can update the script and trigger the prerender.io when the normal user-agent, which means the normal user visits the gallery item. so when the user visits their item and then wanna share their page, the prerender.io cache should be ready

![image](https://user-images.githubusercontent.com/734428/195248082-1b2e08d4-417c-4826-a4cd-6744d8283563.png)

**Comment by preschian** [comment]
seems like I found another alternative

since netlify support prerender by default. so still use similar methods, but request to netlify instead of prerender.io. this is the source https://github.com/preschian/prerender-cf-workers/blob/main/src/index.ts#L23-L33. currently applied on https://kodadot.preschian.xyz/. feel free to test it

sometimes need to wait some seconds to load the open graph. but, at least we can avoid the pricing tier from prerender.io

**Comment by vikiival** [comment]
Can you make a PR to kodadot/workers? so I can deploy it to our CF plan?
