### ISSUE TITLE
Landing page redesign

### ISSUE THREAD

**Issue by XyloDrone** [kodadot/nft-gallery#2792]
### Is your feature request related to a problem?

Hey everyone, seems like we started working on the landing page but never completed it, so maybe it is time to do so :D. 

### Describe the solution you would like

So here’s the priority stuff: 

Design is here (V2 dark>landing): 

https://www.figma.com/file/GeVzZKVORd9L8kAWrlKtZv?

If I missed something in design let me know. One thing I need to do is redesign the NFT cards which have a bit of an odd alignment of info atm. 

Priority tasks
Would be good to add banners to profiles so we can pull them into for featured/curated collections : 

- https://github.com/kodadot/nft-gallery/issues/2329
- https://github.com/kodadot/nft-gallery/issues/1115
- https://github.com/kodadot/nft-gallery/issues/145
- https://github.com/kodadot/nft-gallery/issues/1165
- https://github.com/kodadot/nft-gallery/issues/876
- https://github.com/kodadot/nft-gallery/issues/899
- https://github.com/kodadot/nft-gallery/issues/319
- https://github.com/kodadot/nft-gallery/issues/2776
- https://github.com/kodadot/nft-gallery/issues/2775
- https://github.com/kodadot/nft-gallery/issues/2180
- https://github.com/kodadot/nft-gallery/issues/1445

Later 
- https://github.com/kodadot/nft-gallery/issues/2647 —> when user logs in / connects wallet, to be implemented when we work out the passion feed? Open to suggestions here… we could have a switch to flip between normal landing/passion feed? 

LMK if you wanna work on this and let’s kill the landing craigslist pit :D 

### Describe alternatives you have considered

If anyone has any suggestions about adding/removing stuff from the landing, please be vocal about it :D 

### Screeenshots

<img width="197" alt="Screenshot 2022-04-07 at 14 05 47" src="https://user-images.githubusercontent.com/84407059/162205553-0fa04238-98a4-429e-9d9a-7abd081b2645.png">

**Comment by roiLeo** [comment]
Hey! I've got multiple comments for landing page:

1. would it be possible to have a mobile/tablet version
2. we need to have a "logged" screen and one where it is not "logged in", I'm not for having 2 CTA button in navbar, I suggest that you remove "Create" button if the use is not logged in and vice versa, same for MyProfile link in navbar
3. I would change "Log in" to "Connect"  or "Connect wallet", + can we have a screen where we see the wallet connection modal?
4. Shopping cart is not ready yet and I think it will take a little more time to develop
5. For the links under the first slider where does it takes us?
6. For leaderboard, it's not very pretty to put two tabs next to each other, I would be more into the idea to put tab choice on the left and use something like [radio button](https://buefy.org/documentation/radio#radio-button) on the right side to select a period. What kind of "Volume" will be displayed here?
7. For the nft Card, would it be possible to add a badge in order to know wich type of nft we are looking at (#1744). + Is there something on the design to show me what emote has been attached to the nft?
8. it would be interesting to add the creation date on the "Newest Listed"
9. I don't see "Latest sales" is it on purpose?
10. 10

**Comment by XyloDrone** [comment]
1. Sure, give me a couple of days to make this one. 
2. I'd keep the 2x CTA buttons in the nav bar, maybe move them next to each other so that minting is easily accessible, the majority of other platforms have the same thing, below an example from Rarible: 

![Screenshot 2022-04-13 at 17 24 03](https://user-images.githubusercontent.com/84407059/163226570-1ceb57fc-966e-49ac-a92f-371311847f9c.png)

3. Sure, I'll design these. 

4. no worries, I wouldn't say this is urgent 

5. link on the left side lead to the wiki and the right side to the form through which users can get ksm 

6. Designed that in a similar manner to hic.af and only applied here so that artists/collectors can see stats for both, as well as get an idea of volumes, through the tabs above users can see 1 day, week, month and all time trading volume. 
![Screenshot 2022-04-13 at 17 32 14 1](https://user-images.githubusercontent.com/84407059/163228127-b6974641-1c91-4c3a-94a6-64a0223093b0.png)

7. as in file type like IMAGE, VIDEO, AUDIO? 

8. Sure 

9. Yeah latest sales weren't included but I can do so.

**Comment by XyloDrone** [comment]
@roiLeo srry for the delays with all this stuff, AmsterDot took me by storm :D 

[Here is the design ](https://www.figma.com/file/GeVzZKVORd9L8kAWrlKtZv/?node-id=566%3A4139)for desktop landing(updated everything as per your suggestions).

...and [here](https://www.figma.com/file/GeVzZKVORd9L8kAWrlKtZv/?node-id=564%3A3512) is a mobile version
Let me know your thoughts and if anything else needs to be designed.

**Comment by petersopko** [comment]
Closing this one in favor of
- https://github.com/kodadot/nft-gallery/issues/3844
