### ISSUE TITLE
Seems diagram fails 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2834]
Seems workflow on diagram is failing 🫣

https://github.com/kodadot/nft-gallery/actions/workflows/diagram.yml

![image](https://user-images.githubusercontent.com/5887929/162967606-feaffbfb-7790-410e-8d4e-3d4cb78a4641.png)

**Comment by KngZhi** [comment]
I think the `main` branch is protected by default[1], maybe we need to change the name or setting, like previously using the `main-nuxt`. You can check the [here](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule#creating-a-branch-protection-rule) to found out whether it is protected.

[1]: That's why [alert](https://github.com/kodadot/nft-gallery/runs/5850249677?check_suite_focus=true#step:3:568) shows the action was not authorized.

**Comment by yangwao** [comment]
but could potentially workflow create PR if so?
