### ISSUE TITLE
In user profile adjust showing holdings for Moonsama

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#3182]
Adjust to show data for Moonsama data points

### Ref 
- #3161

**Comment by vikiival** [comment]
[Holdings looks oki](https://beta.kodadot.xyz/moonsama/u/0x59C481548CE7BA13f3288df9f4FCf44a10A589A0?tab=holdings)

<img width="2133" alt="Screenshot 2022-07-09 at 11 55 49" src="https://user-images.githubusercontent.com/22471030/178100864-8dab8fad-ee3e-448b-b3b2-0ec583891373.png">

**Comment by petersopko** [comment]
> [Holdings looks oki](https://beta.kodadot.xyz/moonsama/u/0x59C481548CE7BA13f3288df9f4FCf44a10A589A0?tab=holdings)

hmm seems to work, just one thing tho, when trying to expand the collection with thousands of holdings (such as Pondsama in account you provided), my chrome becomes unresponsive (I assume, the query takes too long?) It loads after a while, but we're talking minutes. Can't even provide network report, since the tab where I'm attempting this just freezes.

**Comment by vikiival** [comment]
> I assume, the query takes too long?

I guess that the query is just poorly written imo
