### ISSUE TITLE
Soft Basilisk launch 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#4003]
this is check list for @vikiival 

- [ ] check prod & critical bugs
- [ ] enable Basilisk in chain selector
- [ ] put Basilisk on Kusama first in the list for convenience for users
- [ ] test if everything works or aren't any obv bugs lurking around 

![image](https://user-images.githubusercontent.com/5887929/191751975-d3a27b77-5486-463c-ada0-61238fa6e582.png)

**Comment by petersopko** [comment]
## Tested on 23/09/2022 (should be fully working after #4008)

- [x] minted collection, shows up in explorer
- [x] minted NFT without price (unlisted)
- [x] minted NFT with price, with no royalty, shows up in explorer
- [x] minted NFT with price, with roylaty, shows up in explorer
- [ ] minted NFT with price, with no royalty, shows up in explorer (waiting for [this comment](https://github.com/kodadot/nft-gallery/pull/4008#issuecomment-1255839670) to get resolved)
  

- [x] bought nft
- [x] made offer on NFT without price (unlisted)
- [x] made offer on NFT with price
- [x] withdrawn expired offer
- [x] withdrawn active offer

- [ ] accept offer (cannot currently do, as I don't have access to two accounts with tokens and I cannot transfer due to transfer bug mentioned below)
- [x] stats show correct data (/offers and /stats)
- [x] switched fees on /assets

critical feature / leftover from switching to multi-token approach:
- #3897 

one thing I'd like to see fixed but isn't critical bug:
- #4010

this one still keeps happening randomly and idk why:
![Pasted image 20220923081959](https://user-images.githubusercontent.com/73316633/191914874-1340d89c-f43e-40be-a30a-bed533caa5ea.png)

**Comment by vikiival** [comment]
> this one still keeps happening randomly and I don't know why:

https://stackoverflow.com/questions/44403930/error-network-error-error-writing-result-to-store-for-query-apollo-client

It would be good to find out which query does that

**Comment by vikiival** [comment]
bsx is running

<img width="1005" alt="Screenshot 2022-09-23 at 12 18 49" src="https://user-images.githubusercontent.com/22471030/191941503-553bedf4-8c4d-4922-a6dc-165cca3c6d0a.png">

**Comment by petersopko** [comment]
> It would be good to find out which query does that

Happened again today, while opening https://beta.kodadot.xyz/snek/explore
