### ISSUE TITLE
Sorting by price does work on Basilisk?

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#4084]
https://beta.kodadot.xyz/bsx/explore?page=1&tab=GALLERY&sort=updatedAt_DESC&sort=blockNumber_DESC&sort=price_ASC&listed=true

Seems like different order by prices than from low to high?

![image](https://user-images.githubusercontent.com/5887929/194067111-9c85dfc3-f65e-4cbd-86cc-de420c08f1b8.png)

**Comment by Jarsen136** [comment]
If several sort options are selected, the first sort condition will take effect.

> https://beta.kodadot.xyz/bsx/explore?page=1&tab=GALLERY&sort=updatedAt_DESC&sort=blockNumber_DESC&sort=price_ASC&listed=true

In this case, the order of nfts is based on `updated time`. If the nfts have the same `updated time`, then they will be sorted based on price.

So, If we would like to see the nfts sorted by priced first, the url would be https://beta.kodadot.xyz/bsx/explore/?page=1&tab=GALLERY&sort=price_ASC&sort=updatedAt_DESC&sort=blockNumber_DESC&listed=true

IMO, the sort options dropdown menu should be changed to a sort options list, so that user could see which sort condition is the first.

**Comment by yangwao** [comment]
ah, in the first place, I'm wondering if having multiple checks was on purpose? 

maybe it's something we can reflect in upcoming redesign of explorer, like having it through some checkbox styles rather than dropdown
