### ISSUE TITLE
Remove beta from logo on official website

### ISSUE THREAD

**Issue by brano-hozza** [kodadot/nft-gallery#4175]
### Is your feature request related to a problem?

I am kinda confused if I am on the official site or the beta version of it

### Describe the solution you would like

I would like to have the pure logo of Koda without the beta sign and keep the beta sign only on the beta webpage

### Describe alternatives you have considered

???

### Screeenshots

<img width="146" alt="image" src="https://user-images.githubusercontent.com/64609060/197785389-6cc76f11-ef90-4413-b882-8f79c5d3c78a.png">

**Comment by Jarsen136** [comment]
Hey, @exezbcz wdyt about this issue?

**Comment by yangwao** [comment]
hey, thanks for reporting! 

I guess hence we have a lot of moving parts even in production, I would stick with the beta labels everywhere. 

It's, for example, same as with Nuxt RC versions, ppl use them in production, so there might still be some dragons, which we have from time to time, so ppl can might sense something might go wrong. 

Of course we are trying our best and when we will have, let's say at least 10+ internal devs, I would be confident removing, bc in case some major fuckup, we will be able quickly react and dispatch a fix. Most of time we did even with little help, but we have still some fragile parts 😅 

Plus we can think of something whenever we will be adjusting logo to have it different way, because greek symbol is probably not way to descriptive for end-user/retail audience :)
