### ISSUE TITLE
New fun facts about the KodaDot ecosystem

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#4349]
We should top up new fun facts about the KodaDot ecosystem. Maybe ambassadors can help us with this? :)

Let's drop down some fun facts you would like to see in KodaDot 😝

@spacesmutje probably know some good ones! :)

<img width="309" alt="image" src="https://user-images.githubusercontent.com/5887929/202473296-d841f839-18b9-40ee-beac-7b7da0f6f4e2.png">

Let's put it into code once we will accumulate at least 10 new fun facts with lot of votes :)

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/issues/4344#issuecomment-1318723441_

**Comment by spacesmutje** [comment]
Fun fact 1:
Did you know that in the first 6 months after opening Subwork Bled, x other teams paid a visit to work on the future of web3?

Fun fact 2:
Did you know that the team of KodaDot attended x events to promote and nurture the idea of the only open-source, cross-chain NFT marketplace?

Fun fact 3:
Did you know that KodaDot created and hosted x events in 2022, with a total of y on-site participants and z views of the video recordings?

Fun fact 4:
Did you know that KodaDog Berry stole x sandwiches and other snacks during events? There might be even more unreported incidents.

Fun fact 5:
Did you know that more than 3400 GMs have been send on Discord until November 2022, since creating the gm-gn-channel in October 2021?

That's it for now, i will try figuring out some more in my creative moments :)

**Comment by spacesmutje** [comment]
> https://github.com/kodadot/nft-gallery/pull/4344#issuecomment-1321950426

No idea what happened here 😅

**Comment by JustLuuuu** [comment]
Did you know that during blockchain events, KodaDog Berry will try to steal your food on average five times?

Did you know that you can find on our Discord a special channel focused only on anime waifus?

**Comment by yangwao** [comment]
Did you know the KodaDot team, in the past months, has given away over two thousand shirts in person?  (correct me if I miscalculated)

Did you know KodaDot has opened co-work in Slovenia and plans to do an offline pop-up gallery with the best talents in Europe for an in-person experience?

Did you know that KodaDot, till recently, has been made only of two power founders?

Did you know that KodaDot has a biking team in Slovenia? You can search for it on Strava.

Did you know that KodaDot has made seven offline events showing KodaDot artists at in-person galleries? 

Did you know that once KodaDot crosses 100 codebase contributors, it will come closer to 200?  

Did you know KodaDot has spent over $200k in bounties to voluntary contributors, including developers?

Did you know KodaDot contributors are working on a better user experience every day?

Did you know KodaDot has API called Uniquery, and developers can start using it?

Did you know KodaDot Github Repository is among top3 active repositories on Kusama network?

**Comment by vikiival** [comment]
Funfacts are deprecated with new loader
