### ISSUE TITLE
Twitter preview of NFT not working (again)

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#5736]
### What happened?

This NFt link: https://kodadot.xyz/rmrk/gallery/17475536-62DB09E2F7FAA81C5F-FLOW-THROW_UP-0000000000000007?page=1 

This link on my Twitter:
https://twitter.com/Just_Luuuu/status/1648995352786108417 

<img width="638" alt="Screenshot 2023-04-20 at 12 22 34" src="https://user-images.githubusercontent.com/104380776/233338181-8d5ccced-4729-4ef7-abed-42bed32c4ce2.png">

Same in chat: 
<img width="352" alt="Screenshot 2023-04-20 at 12 24 40" src="https://user-images.githubusercontent.com/104380776/233338772-adc4048a-cbb0-4eb0-8d1a-c0b8d4e1d539.png">

It should be working on Opengraph: https://www.opengraph.xyz/url/https%3A%2F%2Fkodadot.xyz%2Frmrk%2Fgallery%2F17475536-62DB09E2F7FAA81C5F-FLOW-THROW_UP-0000000000000007

Is this a Twitter issue? Or what am I'm doing wrong?

### Please reproduce in steps

Share NFt on twitter

### Expected Behavior

show preview

### What browsers are you seeing the problem on?

Desktop Chrome

### Are you logged in?

None

### Screenshots

-

### Payment link for reward

https://kodadot.xyz/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yangwao** [comment]
hihi, it worked, maybe something wrong/different with production. 
@preschian can we deploy recent ssr-opengraph-beta to production one?

- #5567 


Also I've noticed I can't open that link on canary in incognito, however I can navigate to that URL through collection
- https://canary.kodadot.xyz/rmrk/gallery/17475536-62DB09E2F7FAA81C5F-FLOW-THROW_UP-0000000000000007

![image](https://user-images.githubusercontent.com/5887929/233348969-c5167418-af97-4252-a755-5723fc166ab6.png)

- On beta it works apparently and doesn't work, suspicious
- https://beta.kodadot.xyz/rmrk/gallery/17475536-62DB09E2F7FAA81C5F-FLOW-THROW_UP-0000000000000007

Probably that's why OG explorer shoots 500 error? @preschian 

![image](https://user-images.githubusercontent.com/5887929/233349549-3b2303ce-f6ee-4148-9963-b1ebcc750f2f.png)

**Comment by yangwao** [comment]
oh, CF might had outage.. 
- https://github.com/kodadot/nft-gallery/issues/5739

**Comment by JustLuuuu** [comment]
looks like its working again <img width="611" alt="Screenshot 2023-04-21 at 13 46 58" src="https://user-images.githubusercontent.com/104380776/233628073-ae39ccc7-fb6a-4c52-8bdd-1c2a51aadf62.png">
