### ISSUE TITLE
Name popular Statemine collections to the sidebar 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#5944]
@JustLuuuu can u drop some popular collections for Statemine 😌

Once merged
- #5935 

Statemine should be available on https://canary.kodadot.xyz

**Comment by JustLuuuu** [comment]
Well because there are only 53 collections on statemine we don't have that many options from which we can choose 😅 
(Im also curious why on Singular there are only 24 collections on Statemine and on KodaDot 53?)

- https://canary.kodadot.xyz/stmn/collection/143?collectionId=143&page=2
- https://canary.kodadot.xyz/stmn/collection/9?collectionId=9 (at the moment problem to load #5974)
- https://canary.kodadot.xyz/stmn/collection/21?collectionId=21
- https://canary.kodadot.xyz/stmn/collection/31848?collectionId=31848
- https://canary.kodadot.xyz/stmn/collection/18?collectionId=18 ETD Denver one
- https://canary.kodadot.xyz/stmn/collection/2?collectionId=2
-https://canary.kodadot.xyz/stmn/collection/10012022?collectionId=10012022

Maybe also: 
- https://canary.kodadot.xyz/stmn/collection/117?collectionId=117 invarch access pass?

**Comment by roiLeo** [comment]
![Screenshot 2023-10-30 at 11-53-53 KodaDot - NFT Market Explorer](https://github.com/kodadot/nft-gallery/assets/9987732/d8ffccf5-f39b-40a9-bbab-140e94ad647f)
