### ISSUE TITLE
Inspect why Sentry plugin breaks builds on CloudFlare Pages

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#6518]
@preschian Okay, it's a sentry plugin. Seems builds.  

- https://github.com/nuxt-community/sentry-module

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/issues/6470#issuecomment-1662093932_

**Comment by preschian** [comment]
result from my forked repo
- netlify: ok
- vercel: ok
- cf-pages: error

It seems like a compatibility issue with current `nitro` version on cf-pages
or
there is something wrong on cf-pages

**Comment by yangwao** [comment]
We are so back when I've added Sentry AUTH token 

```
18:51:49.040 | ^
-- | --
18:51:49.057 | 34099:       "img/logo-talisman.4e0808a.svg",
18:51:49.057 | 34100:       "img/logo-enkrypt.8a571eb.png",
18:51:49.058 | [fatal] Unexpected token (Note that you need plugins to import files that are not JavaScript)
18:51:49.058 | at error (node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:1858:30)
18:51:49.058 | at Module.error (node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:12429:16)
18:51:49.058 | at Module.tryParse (node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:12806:25)
18:51:49.058 | at Module.setSource (node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:12711:24)
18:51:49.059 | at ModuleLoader.addModuleSource (node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:21959:20)
18:51:49.158 | Finished
18:51:49.158 | Note: No functions dir at /functions found. Skipping.
18:51:49.159 | Validating asset output directory
18:51:52.017 | Deploying your site to Cloudflare's global network...
18:51:53.228 | Parsed 1 valid header rule.
18:51:55.620 | Uploading... (361/368)
18:51:56.220 | Uploading... (363/368)
18:51:57.518 | Uploading... (365/368)
18:51:58.623 | Uploading... (368/368)
18:51:58.624 | ✨ Success! Uploaded 7 files (361 already uploaded) (4.11 sec)
18:51:58.624 |  
18:51:59.319 | ✨ Upload complete!
18:52:07.529 | Success: Assets published!
18:52:08.578 | Success: Your site was deployed!
```

**Comment by preschian** [comment]
> We are so back when I've added Sentry AUTH token

hhmm, interesting 🤔

I added `SENTRY_AUTH_TOKEN` in preview branch (`test-cf-preview`), seems fine

<details><summary>Details</summary>
<p>

![image](https://github.com/kodadot/nft-gallery/assets/734428/be731f99-64e4-490f-821d-df92e59e7ccf)

</p>
</details>

**Comment by preschian** [comment]
maybe @prury want to test also?

how to test:
1. fork nft-gallery
2. create an account on cloudflare pages
3. integrate forked nft-gallery to cloudflare pages
4. add `SENTRY_AUTH_TOKEN` as env

send me a discord message if you need pairing

**Comment by prury** [comment]
> maybe @prury want to test also?
> 
> how to test:
> 
>     1. fork nft-gallery
> 
>     2. create an account on cloudflare pages
> 
>     3. integrate forked nft-gallery to cloudflare pages
> 
>     4. add `SENTRY_AUTH_TOKEN` as env
> 
> 
> send me a discord message if you need pairing

yup! will need your assistance

**Comment by preschian** [comment]
oh, now, breaks on netlify deployment https://app.netlify.com/sites/koda-canary/deploys/64d1fb67f867ea0007170f88

**Comment by preschian** [comment]
Now, it is an intermittent error, and we need to retry the deployment if show up the error again. I don't know what the root cause is 🥲

It's time to move to Vite, I guess. Currently, we are still using webpack in nuxt-bridge

**Comment by preschian** [comment]
I will remove `SENTRY_AUTH_TOKEN` in preview branch for now

**Comment by preschian** [comment]
It would be good if someone could find the root cause cc @kodadot/internal-dev 

For context: there are no changes from the Cloudflare pages dashboard, but somehow when trying to deploy it to production, it throws the error. first occurrence https://github.com/kodadot/nft-gallery/issues/6470#issue-1820619937

**Comment by yangwao** [comment]
> I will remove `SENTRY_AUTH_TOKEN` in preview branch for now

Yes, please leave it w/o SENTRY token, I prefer working build than reporting Sentry from broken build 😄 
I hope we'll figure out tbh, maybe some issue on our side.

- #2690 

Probably time to check on Vite too
- https://github.com/kodadot/nft-gallery/issues/1418

**Comment by preschian** [comment]
Confusing part was it fine on my forked version https://main.nft-gallery-1hj.pages.dev/

wanna try to upload it through gh-actions? @yangwao 
run `pnpm generate` on gh-actions, and then upload it using this https://github.com/cloudflare/pages-action

**Comment by preschian** [comment]
> wanna try to upload it through gh-actions? @yangwao run `pnpm generate` on gh-actions, and then upload it using this [cloudflare/pages-action](https://github.com/cloudflare/pages-action)

oh nvm, it also error on github actions

![image](https://github.com/kodadot/nft-gallery/assets/734428/b87e5a85-d5ad-43d9-96a8-9805511618eb)

**Comment by yangwao** [comment]
> wanna try to upload it through gh-actions? @yangwao
> run `pnpm generate` on gh-actions, and then upload it using this [cloudflare/pages-action](https://github.com/cloudflare/pages-action)

uh sounds pretty complicated, keep it simple 😄

**Comment by preschian** [comment]
## The Journey

Hi, I want to share my journey here after trying some stuff to validate the assumptions. Here are some assumptions that seem not valid

#### 1. `SENTRY_AUTH_TOKEN` was the problem. Ref: https://github.com/kodadot/nft-gallery/issues/6470#issuecomment-1662083473.

Last week, I thought that was the main problem. Because, in the previous week, the build worked well after we removed that from environment variables. Unfortunately, last night we faced the same error again, even though we pulled the env

You can see in the screenshot below that I only put `PNPM_VERSION` in the environment variables section. But the build still has an error in the "Build log" section.

<details><summary>screenshot fail</summary>
<p>

![image](https://github.com/kodadot/nft-gallery/assets/734428/7ef3bc7b-f02a-4d20-8306-cda227d48f3c)

</p>
</details> 

Then I just retried several times until it worked. You can see this in the screenshot below. Same env, same code, and then the build works

<details><summary>screenshot success</summary>
<p>

![image](https://github.com/kodadot/nft-gallery/assets/734428/a69355f0-98ba-43a1-9312-7fa5ea14c7c5)


</p>
</details> 

I already tried to remove sentry-related packages also, but it still fails. Here is the [commit](https://github.com/preschian/nft-gallery/pull/99/commits/c4ae4dc5c2f2bb8c97fce762ee02354a8810ab1d). Here is the [gh-actions logs](https://github.com/preschian/nft-gallery/actions/runs/5829806142/job/15809968805). Here is [the PR](https://github.com/preschian/nft-gallery/pull/99/commits).

#### 2. Cloudflare Pages was the problem. Ref: https://github.com/kodadot/nft-gallery/issues/6518#issuecomment-1663354318

I thought that the error was only in the Cloudflare Pages. But, I discovered that it could also be an error on netlify, even locally.

error logs on netlify: https://app.netlify.com/sites/koda-canary/deploys/64d1fb67f867ea0007170f88

error logs on gh-actions: https://github.com/kodadot/nft-gallery/actions/runs/5830455843/job/15811865669

<details><summary>error logs on my local</summary>
<p>

![Screenshot 2023-08-11 135903](https://github.com/kodadot/nft-gallery/assets/734428/940ed973-08f2-44fa-b677-6a5f6026e160)

</p>
</details> 

The tricky part, the error was intermittent and did not correctly return [the exit code](https://nodejs.org/api/process.html#processexitcode). So, even though the build was incomplete, CI continued the process. If the error returns the exit code correctly, we can detect the mistake early in our gh-actions.

## Last Assumptions

I think that our **build steps are within the limits**. I found that someone also tried to reduce the total generated files in `nuxt generate`. Ref: https://stackoverflow.com/q/71890697

Here is another attempt related to building steps
- https://github.com/kodadot/nft-gallery/pull/6671

## Moving forward to Nuxt3

I hope we can find a way to use Nuxt3 + Vite immediately. So far, I have only one option to use Nuxt3 https://github.com/kodadot/nft-gallery/discussions/6429 right away. But, tbh, I want that POC for the last option because the most significant downside of my POC was that we needed to create a component from scratch.

Feel free to share if someone has a better alternative to migrate to Nuxt3.

**Comment by yangwao** [comment]
> I think that our **build steps are within the limits**.

We hit this because we are trying to process too many components at once or..? I haven't slept well today, so asking 😄

**Comment by vikiival** [comment]
> I haven't slept well today, so asking 😄

Imo what was mentioned in SO is that cloudlfare has limits for files

https://developers.cloudflare.com/pages/platform/limits/

and every component and async component is separated file + blog assets & so

**Comment by preschian** [comment]
> We hit this because we are trying to process too many components at once or..?

Something like that. between so heavy to process or too many files

> I haven't slept well today, so asking 😄

😅😅😅

**Comment by preschian** [comment]
> > I haven't slept well today, so asking 😄
> 
> Imo what was mentioned in SO is that cloudlfare has limits for files
> 
> [developers.cloudflare.com/pages/platform/limits](https://developers.cloudflare.com/pages/platform/limits/)

this is also could be possible the problem for them in Stackoverflow case

**Comment by yangwao** [comment]
> and every component and async component is separated file + blog assets & so

There are limit 20k files, I usually see low as 6xx files being uploaded. Then it must be something else I guess?

**Comment by preschian** [comment]
Correct, I'm sure the error in our app is not related to limits on Cloudflare Pages. Because we have evidence that we can face the error on gh-actions, netlify, and even locally. So, I assume there is something related to building steps in our app.

For the person in [Stackoverflow](https://stackoverflow.com/q/71890697), it might be the issue is from limits on cf-pages
