### ISSUE TITLE
Randomize generation for every user 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#8324]
- refresh the generation on entry for every user 
- currently, some user got the same generation and actually minted it, resulting in duplicates 
![image](https://github.com/kodadot/nft-gallery/assets/90852205/8851affc-fa3a-4932-b8ba-886b2186950e)

**Comment by Jarsen136** [comment]
> * currently, some user got the same generation and actually minted it, resulting in duplicates
>  
It should be because `screenshot service` failed, and then it fallback to the default image( the same image as the collection). 

https://github.com/kodadot/nft-gallery/blob/f865870b2c9de496e42458b01c6d23fd11c8690a/components/collection/drop/Generative.vue#L213


<img width="1480" alt="image" src="https://github.com/kodadot/nft-gallery/assets/31397967/2407d839-e9cf-4f53-9506-2d3f8ac3506d">

**Comment by yangwao** [comment]
this was screenshot service failure
