### ISSUE TITLE
fix Sentry for production & beta

### ISSUE THREAD

**Issue by roiLeo** [kodadot/nft-gallery#8532]
No particular events in the last 30days, sus

**Comment by yangwao** [comment]
lol can we fix it please

**Comment by roiLeo** [comment]
> lol can we fix it please

is en var set on:
- cloudflare beta/canary?
- netlify preview?

**Comment by yangwao** [comment]
no, let's set it under `SENTRY`

**Comment by yangwao** [comment]
on netlify is but looks diferently tho

**Comment by yangwao** [comment]
set only for preview for CF, don't want to ruin cloudflare production

**Comment by roiLeo** [comment]
hmmmmm

![Screenshot 2023-12-19 at 16-58-18 Auth Tokens — Sentry](https://github.com/kodadot/nft-gallery/assets/9987732/23250818-471c-443f-be5b-9098a8511d62)

**Comment by yangwao** [comment]
@roiLeo do u think events limits is issue? yet i don't see any logged in for while
![image](https://github.com/kodadot/nft-gallery/assets/5887929/722e262b-58bb-4192-8a7d-2f354c5853bf)

**Comment by roiLeo** [comment]
> @roiLeo do u think events limits is issue? yet i don't see any logged in for while
> ![image](https://github.com/kodadot/nft-gallery/assets/5887929/722e262b-58bb-4192-8a7d-2f354c5853bf)
> 

This was me, dont mind the notif

**Comment by roiLeo** [comment]
Maybe check build logs on cloudflare if there is no:
```log
[log] [sentry-vite-plugin] Warning: No auth token provided.
```

**Comment by yangwao** [comment]
Seems I see some events? 

![image](https://github.com/kodadot/nft-gallery/assets/5887929/cf2e1d61-0025-4fe4-a35f-eccb9c219dff)

**Comment by yangwao** [comment]
> Maybe check build logs on cloudflare if there is no:

cc @preschian

**Comment by roiLeo** [comment]
> Seems I see some events?

This comes from old deploy preview e.g. #6364

**Comment by preschian** [comment]
I guess we can't put the key in the `Preview` since we are using these domains on the `Production` build.

<img width="308" alt="image" src="https://github.com/kodadot/nft-gallery/assets/734428/4a691084-a681-4432-bc6b-a546c3a1b5e3">

Is it okay if I put the key on the production build? This means it affects all of those custom domains.

**Comment by yangwao** [comment]
> Is it okay if I put the key on the production build?

I guess, so, better than nothing tbh

**Comment by preschian** [comment]
> I guess, so, better than nothing tbh

Added, sorry for the late response

*been food poisoning these days 🤢

**Comment by yangwao** [comment]
> *been food poisoning these days 🤢

get well; seems lot of our team members got these day hiccups (health), even I do, need to be strong 💪🏾 and mindful of daily risks, hopefully will be okay or already is :)

**Comment by yangwao** [comment]
I've canceled as since August doesn't work at all, no need to pay it, we can reintroduce it anytime we will have time.

![image](https://github.com/kodadot/nft-gallery/assets/5887929/39893eaf-079b-4124-99ce-1341038ece35)
![image](https://github.com/kodadot/nft-gallery/assets/5887929/edf4ac49-3a56-48f3-a870-23e203985faf)
