### ISSUE TITLE
Unable to set system theme if you enable dark/light manually

### ISSUE THREAD

**Issue by shashkovdanil** [kodadot/nft-gallery#8554]
### Is your feature request related to a problem?

If I manually switch the theme, I can't get the system theme back, which can be inconvenient

### Describe the solution you would like

Usually, the theme switch has three states:

1. Dark theme
2. Light theme
3. Automatic theme (taken from the system).

**Comment by roiLeo** [comment]
> If I manually switch the theme, I can't get the system theme back, which can be inconvenient

isn't it excepted result?

Let take for example a case:
- user has dark mode in browser preference
- first navigation on Kodadot -> should be dark ✔️ 
- change to light mode because user like Kodadot light mode ✔️ 
- now user close brower, and when reopen Kodadot should be light mode instead of browser preference

**Comment by roiLeo** [comment]
> We have to save the selected theme locally

`nuxt-color-mode` handle this

What's your concern with the theme feature? we've never had a problem with it, don't loose to much time focus on something derisory
