### ISSUE TITLE
Previews on landing page - spotlight section 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#8663]
![image](https://github.com/kodadot/nft-gallery/assets/90852205/cabdf43d-21e1-49e4-9411-719d69430f64)
- whatsupp with these previews? 
![image](https://github.com/kodadot/nft-gallery/assets/90852205/833f080d-8b52-43ac-8976-3b09a7d45111)

the cover img (same as profile picture) looks oki 
![image](https://github.com/kodadot/nft-gallery/assets/90852205/b54b2ba0-b7b6-45b7-b690-b64e23bdf68d)
https://canary.kodadot.xyz/ahp/collection/56

**Comment by prury** [comment]
I think they don't look good inside gallery item as well, its cutting the image

<img src="https://github.com/kodadot/nft-gallery/assets/36627808/aeb91984-83b0-4169-ab75-d0fb53e724b2" height="400">

**Comment by JustLuuuu** [comment]
Spotlight in AHP is not selected. Its automatically showing the NEWEST collections minted. On ahk and other chains we had manually selected collections. On AHP it was not necessary because there were not many collections there.

In case you want to have spotlighted our collections, we can open an issue for it, guys can do it pretty quickly. Just prepare a list of collections you like. Or maybe they will be able to put only KodaDot Minter collections there.

**Comment by roiLeo** [comment]
will be closed by #8672
