### ISSUE TITLE
nfts.AlreadyExists drop page mint 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#9550]
![image](https://github.com/kodadot/nft-gallery/assets/90852205/f9585895-9111-4912-a4f3-384299ac6ba9)
- not sure if already reported, this still shows 

yeah, the nft did not mint

did not happen on production, but on canary

**Comment by preschian** [comment]
@exezbcz how about try again? and give me the address, will check

**Comment by daiagi** [comment]
Could not reproduce

**Comment by exezbcz** [comment]
@preschian 
> did not happen on production, but on canary

tried on production

its hard to reproduce, cannot find a way how to make it consistently appear 


address: 1cQB9WUTtwyH3H4Ksn7pLfJvMLCxtzQHbUNhZtVBasoX3X9

**Comment by hassnian** [comment]
same

![CleanShot 2024-02-29 at 15 19 20@2x](https://github.com/kodadot/nft-gallery/assets/44554284/cfd3e99b-ca28-4563-a5f8-68f20a9bd988)

/ahk/drops/reflection

DYc9cY7q7UA3Rq97HtiobrLNbMbZgepATJtn3fzPE2jf5v6

**Comment by preschian** [comment]
For @hassnian case. Db and on-chain data were different. It seems like you will be stuck to mint NFT with sn 32. Could you try again on Canary and monitor the request parameters to `fxart`? I will edit it on the DB side if it is still stuck. But I'm not sure what the root cause is. Meanwhile, 32 is already claimed: https://canary.kodadot.xyz/ahk/gallery/377-32.

<img width="788" alt="image" src="https://github.com/kodadot/nft-gallery/assets/734428/df483360-90db-40bd-bb91-df417e8caa8c">

For @exezbcz, could you try again on Canary? I assume this one is a `fields` drop? Next mint should get one of these IDs.

<img width="831" alt="image" src="https://github.com/kodadot/nft-gallery/assets/734428/71f9cafd-7856-4bd8-a075-3323c3f4aece">
