### ISSUE TITLE
Tests shards (2,6) looks broke

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#9694]
what's about tests?

seems it's on multiple PRs 

![image](https://github.com/kodadot/nft-gallery/assets/5887929/d10681d7-5520-4282-82b3-30bbfe39cfba)

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/issues/9675#issuecomment-1987216567_

**Comment by prury** [comment]
yeah, so strage, its giving me react error code??

![image](https://github.com/kodadot/nft-gallery/assets/36627808/541b08b5-f6ff-455e-b161-58ec8cc125a1)

`Error: Failing test due to error in browser: Error: Minified React error #419; visit https://reactjs.org/docs/error-decoder.html?invariant=419 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.`

`The server could not finish this Suspense boundary, likely due to an error during server rendering. Switched to client rendering.`
